// AUTO-GENERATED from src/assets/data.xls — do not edit by hand
// Run: python scripts/convert_xls.py
const maharashtraData = {
  "Ahmednagar": [
    "Ahmadnagar",
    "Akola",
    "Jamkhed",
    "Karjat",
    "Kopargaon",
    "Nagar",
    "Nevasa",
    "Parner",
    "Pathardi",
    "Rahta",
    "Rahuri",
    "Sangamner",
    "Shevgaon",
    "Shrigonda",
    "Shrirampur"
  ],
  "Akola": [
    "Akola",
    "Akot",
    "Balapur",
    "Barshitakli",
    "Murtijapur",
    "Patur",
    "Telhara"
  ],
  "Amravati": [
    "Achalpur",
    "Amravati",
    "Anjangaon Surji",
    "Bhatkuli",
    "Chandur Railway",
    "Chandurbazar",
    "Chikhaldara",
    "Daryapur",
    "Dhamangaon Railway",
    "Dharni",
    "Morshi",
    "Nandgaon-Khandeshwar",
    "Teosa",
    "Warud"
  ],
  "Aurangabad": [
    "Aurangabad",
    "Gangapur",
    "Kannad",
    "Khuldabad",
    "Paithan",
    "Phulambri",
    "Sillod",
    "Soegaon",
    "Vaijapur"
  ],
  "Beed": [
    "Ambejogai",
    "Ashti",
    "Bid",
    "Dharur",
    "Georai",
    "Kaij",
    "Manjlegaon",
    "Parli",
    "Patoda",
    "Shirur (Kasar)",
    "Wadwani"
  ],
  "Bhandara": [
    "Bhandara",
    "Lakhandur",
    "Lakhani",
    "Mohadi",
    "Pauni",
    "Sakoli",
    "Tumsar"
  ],
  "Buldhana": [
    "Buldana",
    "Chikhli",
    "Deolgaon Raja",
    "Jalgaon (Jamod)",
    "Khamgaon",
    "Lonar",
    "Malkapur",
    "Mehkar",
    "Motala",
    "Nandura",
    "Sangrampur",
    "Shegaon",
    "Sindkhed Raja"
  ],
  "Chandrapur": [
    "Ballarpur",
    "Bhadravati",
    "Brahmapuri",
    "Chandrapur",
    "Chimur",
    "Gondpipri",
    "Jiwati",
    "Korpana",
    "Mul",
    "Nagbhir",
    "Pombhurna",
    "Rajura",
    "Sawali",
    "Sindewahi",
    "Warora"
  ],
  "Dhule": [
    "Dhule",
    "Sakri",
    "Shirpur",
    "Sindkhede"
  ],
  "Gadchiroli": [
    "Aheri",
    "Armori",
    "Bhamragad",
    "Chamorshi",
    "Desaiganj (Vadasa)",
    "Dhanora",
    "Etapalli",
    "Gadchiroli",
    "Korchi",
    "Kurkheda",
    "Mulchera",
    "Sironcha"
  ],
  "Gondia": [
    "Amgaon",
    "Arjuni Morgaon",
    "Deori",
    "Gondiya",
    "Goregaon",
    "Sadak-Arjuni",
    "Salekasa",
    "Tirora"
  ],
  "Hingoli": [
    "Aundha (Nagnath)",
    "Basmath",
    "Hingoli",
    "Kalamnuri",
    "Sengaon"
  ],
  "Jalgaon": [
    "Amalner",
    "Bhadgaon",
    "Bhusawal",
    "Bodvad",
    "Chalisgaon",
    "Chopda",
    "Dharangaon",
    "Erandol",
    "Jalgaon",
    "Jamner",
    "Muktainagar",
    "Pachora",
    "Parola",
    "Raver",
    "Yawal"
  ],
  "Jalna": [
    "Ambad",
    "Badnapur",
    "Bhokardan",
    "Ghansawangi",
    "Jafferabad",
    "Jalna",
    "Mantha",
    "Partur"
  ],
  "Kolhapur": [
    "Ajra",
    "Bavda",
    "Bhudargad",
    "Chandgad",
    "Gadhinglaj",
    "Hatkanangle",
    "Kagal",
    "Karvir",
    "Kolhapur",
    "Panhala",
    "Radhanagari",
    "Shahuwadi",
    "Shirol"
  ],
  "Latur": [
    "Ahmadpur",
    "Ausa",
    "Chakur",
    "Deoni",
    "Jalkot",
    "Latur",
    "Nilanga",
    "Renapur",
    "Shirur-Anantpal",
    "Udgir"
  ],
  "Mumbai City": [
    "Area not under any Sub-district",
    "Mumbai"
  ],
  "Mumbai Suburban": [
    "Area not under any Sub-district",
    "Mumbai Suburban"
  ],
  "Nagpur": [
    "Bhiwapur",
    "Hingna",
    "Kalameshwar",
    "Kamptee",
    "Katol",
    "Kuhi",
    "Mauda",
    "Nagpur",
    "Nagpur (Rural)",
    "Nagpur (Urban)",
    "Narkhed",
    "Parseoni",
    "Ramtek",
    "Savner",
    "Umred"
  ],
  "Nanded": [
    "Ardhapur",
    "Bhokar",
    "Biloli",
    "Deglur",
    "Dharmabad",
    "Hadgaon",
    "Himayatnagar",
    "Kandhar",
    "Kinwat",
    "Loha",
    "Mahoor",
    "Mudkhed",
    "Mukhed",
    "Naigaon (Khairgaon)",
    "Nanded",
    "Umri"
  ],
  "Nandurbar": [
    "Akkalkuwa",
    "Akrani",
    "Nandurbar",
    "Nawapur",
    "Shahade",
    "Talode"
  ],
  "Nashik": [
    "Baglan",
    "Chandvad",
    "Deola",
    "Dindori",
    "Igatpuri",
    "Kalwan",
    "Malegaon",
    "Nandgaon",
    "Nashik",
    "Niphad",
    "Peint",
    "Sinnar",
    "Surgana",
    "Trimbakeshwar",
    "Yevla"
  ],
  "Osmanabad": [
    "Bhum",
    "Kalamb",
    "Lohara",
    "Osmanabad",
    "Paranda",
    "Tuljapur",
    "Umarga",
    "Washi"
  ],
  "Parbhani": [
    "Gangakhed",
    "Jintur",
    "Manwath",
    "Palam",
    "Parbhani",
    "Pathri",
    "Purna",
    "Sailu",
    "Sonpeth"
  ],
  "Pune": [
    "Ambegaon",
    "Baramati",
    "Bhor",
    "Daund",
    "Haveli",
    "Indapur",
    "Junnar",
    "Khed",
    "Mawal",
    "Mulshi",
    "Pune",
    "Pune City",
    "Purandhar",
    "Shirur",
    "Velhe"
  ],
  "Raigad": [
    "Alibag",
    "Karjat",
    "Khalapur",
    "Mahad",
    "Mangaon",
    "Mhasla",
    "Murud",
    "Panvel",
    "Pen",
    "Poladpur",
    "Raigarh",
    "Roha",
    "Shrivardhan",
    "Sudhagad",
    "Tala",
    "Uran"
  ],
  "Ratnagiri": [
    "Chiplun",
    "Dapoli",
    "Guhagar",
    "Khed",
    "Lanja",
    "Mandangad",
    "Rajapur",
    "Ratnagiri",
    "Sangameshwar"
  ],
  "Sangli": [
    "Atpadi",
    "Jat",
    "Kadegaon",
    "Kavathemahankal",
    "Khanapur (Vita)",
    "Miraj",
    "Palus",
    "Sangli",
    "Shirala",
    "Tasgaon",
    "Walwa"
  ],
  "Satara": [
    "Jaoli",
    "Karad",
    "Khandala",
    "Khatav",
    "Koregaon",
    "Mahabaleshwar",
    "Man",
    "Patan",
    "Phaltan",
    "Satara",
    "Wai"
  ],
  "Sindhudurg": [
    "Devgad",
    "Dodamarg",
    "Kankavli",
    "Kudal",
    "Malwan",
    "Sawantwadi",
    "Sindhudurg",
    "Vaibhavvadi",
    "Vengurla"
  ],
  "Solapur": [
    "Akkalkot",
    "Barshi",
    "Karmala",
    "Madha",
    "Malshiras",
    "Mangalvedhe",
    "Mohol",
    "Pandharpur",
    "Sangole",
    "Solapur",
    "Solapur North",
    "Solapur South"
  ],
  "Thane": [
    "Ambarnath",
    "Bhiwandi",
    "Dahanu",
    "Jawhar",
    "Kalyan",
    "Mokhada",
    "Murbad",
    "Palghar",
    "Shahapur",
    "Talasari",
    "Thane",
    "Ulhasnagar",
    "Vada",
    "Vasai",
    "Vikramgad"
  ],
  "Wardha": [
    "Arvi",
    "Ashti",
    "Deoli",
    "Hinganghat",
    "Karanja",
    "Samudrapur",
    "Seloo",
    "Wardha"
  ],
  "Washim": [
    "Karanja",
    "Malegaon",
    "Mangrulpir",
    "Manora",
    "Risod",
    "Washim"
  ],
  "Yavatmal": [
    "Arni",
    "Babulgaon",
    "Darwha",
    "Digras",
    "Ghatanji",
    "Kalamb",
    "Kelapur",
    "Mahagaon",
    "Maregaon",
    "Ner",
    "Pusad",
    "Ralegaon",
    "Umarkhed",
    "Wani",
    "Yavatmal",
    "Zari-Jamani"
  ]
};

export const districts = Object.keys(maharashtraData).sort();

export const getTalukas = (district) => maharashtraData[district] || [];

export default maharashtraData;
