// District → Taluka → Villages (major gram panchayats & towns)
// "इतर" option Section1 mein add hoga manually
const villageData = {
  "Ahmednagar": {
    "Ahmednagar": ["Ahmednagar","Savedi","Bhingar","Puntamba","Newasa","Ghargaon"],
    "Akole": ["Akole","Rajur","Sangamner","Ghoti","Brahmani","Kothari"],
    "Jamkhed": ["Jamkhed","Mhaswad","Karjat","Akluj","Pargaon"],
    "Karjat": ["Karjat","Pargaon","Nimbodi","Ghodegaon"],
    "Kopargaon": ["Kopargaon","Savargaon","Pimpalgaon Baswant","Vambori"],
    "Newasa": ["Newasa","Ghargaon","Sonai","Pathardi"],
    "Parner": ["Parner","Belvandi","Kanhur Mesai","Malegaon"],
    "Pathardi": ["Pathardi","Mirajgaon","Kanhegaon"],
    "Rahata": ["Rahata","Shirdi","Samsherpur","Vambori"],
    "Rahuri": ["Rahuri","Akolner","Dahigaon","Nagapur"],
    "Sangamner": ["Sangamner","Ghoti","Mhalsapuri","Nighoj"],
    "Shevgaon": ["Shevgaon","Bodhegaon","Varudi"],
    "Shrigonda": ["Shrigonda","Bhalwani","Karjat"],
    "Shrirampur": ["Shrirampur","Belapur","Loni","Savargaon"],
  },
  "Akola": {
    "Akola": ["Akola","Murtizapur","Barshitakli","Borgaon Manju"],
    "Akot": ["Akot","Dahihanda","Kurankhed"],
    "Balapur": ["Balapur","Borgaon","Sindkhed"],
    "Barshitakli": ["Barshitakli","Kanheri Sarap","Nimba"],
    "Murtizapur": ["Murtizapur","Poha","Umara"],
    "Patur": ["Patur","Dahihanda","Kurankhed"],
    "Telhara": ["Telhara","Borgaon","Nandura"],
  },
  "Amravati": {
    "Amravati": ["Amravati","Badnera","Nandgaon Peth","Paratwada"],
    "Achalpur": ["Achalpur","Paratwada","Chandur Bazar"],
    "Anjangaon Surji": ["Anjangaon Surji","Dhamangaon","Morshi"],
    "Chandur Bazar": ["Chandur Bazar","Nandgaon","Payagad"],
    "Chandur Railway": ["Chandur Railway","Warud","Amla"],
    "Chikhaldara": ["Chikhaldara","Semadoh","Dharni"],
    "Daryapur": ["Daryapur","Shendurjana","Nandgaon Peth"],
    "Dhamangaon Railway": ["Dhamangaon Railway","Badnera","Amravati"],
    "Morshi": ["Morshi","Warud","Chandur"],
    "Nandgaon Khandeshwar": ["Nandgaon Khandeshwar","Dhamangaon","Teosa"],
    "Teosa": ["Teosa","Dhamangaon","Chandur"],
    "Warud": ["Warud","Morshi","Amla"],
  },
  "Aurangabad": {
    "Aurangabad": ["Aurangabad","Waluj","Cidco","Satara"],
    "Gangapur": ["Gangapur","Shendi","Paithan","Georai"],
    "Kannad": ["Kannad","Sillod","Soygaon","Phulambri"],
    "Khuldabad": ["Khuldabad","Rauza","Ellora","Daulatabad"],
    "Paithan": ["Paithan","Shendi","Nandura","Georai"],
    "Phulambri": ["Phulambri","Sillod","Kannad"],
    "Sillod": ["Sillod","Kannad","Phulambri","Soygaon"],
    "Soegaon": ["Soegaon","Sillod","Kannad"],
    "Vaijapur": ["Vaijapur","Lasur","Waluj","Kopargaon"],
  },
  "Beed": {
    "Ambajogai": ["Ambajogai","Latur","Parli","Dharur"],
    "Ashti": ["Ashti","Wadwani","Patoda"],
    "Beed": ["Beed","Majalgaon","Gevrai"],
    "Dharur": ["Dharur","Latur","Nilanga"],
    "Georai": ["Georai","Beed","Majalgaon"],
    "Kaij": ["Kaij","Dharur","Latur"],
    "Majalgaon": ["Majalgaon","Beed","Georai","Latur"],
    "Parli": ["Parli","Ambajogai","Latur"],
    "Patoda": ["Patoda","Ashti","Wadwani"],
    "Shirur Kasar": ["Shirur Kasar","Beed","Majalgaon"],
    "Wadwani": ["Wadwani","Ashti","Patoda"],
  },
  "Buldhana": {
    "Buldhana": ["Buldhana","Chikhli","Shegaon","Sindkhed Raja"],
    "Chikhli": ["Chikhli","Buldhana","Nandura"],
    "Deulgaon Raja": ["Deulgaon Raja","Khamgaon","Malkapur"],
    "Jalgaon Jamod": ["Jalgaon Jamod","Buldana","Sangrampur"],
    "Khamgaon": ["Khamgaon","Malkapur","Shegaon"],
    "Lonar": ["Lonar","Mehkar","Sindkhed Raja"],
    "Malkapur": ["Malkapur","Khamgaon","Shegaon"],
    "Mehkar": ["Mehkar","Lonar","Sindkhed Raja"],
    "Motala": ["Motala","Buldhana","Chikhli"],
    "Nandura": ["Nandura","Chikhli","Buldhana"],
    "Sangrampur": ["Sangrampur","Jalgaon Jamod","Buldhana"],
    "Shegaon": ["Shegaon","Khamgaon","Malkapur"],
    "Sindkhed Raja": ["Sindkhed Raja","Lonar","Mehkar"],
  },
  "Dhule": {
    "Dhule": ["Dhule","Shirpur","Sakri","Sindkheda"],
    "Sakri": ["Sakri","Dhule","Nandurbar"],
    "Shirpur": ["Shirpur","Dhule","Navapur"],
    "Sindkheda": ["Sindkheda","Dhule","Sakri"],
  },
  "Gondia": {
    "Amgaon": ["Amgaon","Gondia","Tirora"],
    "Arjuni Morgaon": ["Arjuni Morgaon","Gondia","Sadak Arjuni"],
    "Deori": ["Deori","Gondia","Salekasa"],
    "Gondiya": ["Gondia","Amgaon","Tirora","Goregaon"],
    "Goregaon": ["Goregaon","Gondia","Salekasa"],
    "Sadak Arjuni": ["Sadak Arjuni","Arjuni Morgaon","Gondia"],
    "Salekasa": ["Salekasa","Gondia","Deori"],
    "Tirora": ["Tirora","Gondia","Amgaon"],
  },
  "Hingoli": {
    "Aundha Nagnath": ["Aundha Nagnath","Hingoli","Basmath"],
    "Basmath": ["Basmath","Hingoli","Sengaon"],
    "Hingoli": ["Hingoli","Basmath","Kalamnuri"],
    "Kalamnuri": ["Kalamnuri","Hingoli","Sengaon"],
    "Sengaon": ["Sengaon","Hingoli","Basmath"],
  },
  "Jalgaon": {
    "Amalner": ["Amalner","Dharangaon","Chopda"],
    "Bhadgaon": ["Bhadgaon","Chalisgaon","Nandgaon"],
    "Bhusawal": ["Bhusawal","Jalgaon","Bodwad"],
    "Bodwad": ["Bodwad","Bhusawal","Jalgaon"],
    "Chalisgaon": ["Chalisgaon","Bhadgaon","Nandgaon"],
    "Chopda": ["Chopda","Amalner","Shirpur"],
    "Dharangaon": ["Dharangaon","Amalner","Erandol"],
    "Erandol": ["Erandol","Dharangaon","Jalgaon"],
    "Jalgaon": ["Jalgaon","Bhusawal","Bodwad"],
    "Jamner": ["Jamner","Jalgaon","Muktainagar"],
    "Muktainagar": ["Muktainagar","Erandol","Jalgaon"],
    "Pachora": ["Pachora","Chalisgaon","Jalgaon"],
    "Parola": ["Parola","Amalner","Dharangaon"],
    "Raver": ["Raver","Muktainagar","Yawal"],
    "Yawal": ["Yawal","Raver","Muktainagar"],
  },
  "Jalna": {
    "Ambad": ["Ambad","Jalna","Badnapur"],
    "Badnapur": ["Badnapur","Jalna","Ambad"],
    "Bhokardan": ["Bhokardan","Jalna","Mantha"],
    "Ghansawangi": ["Ghansawangi","Jalna","Partur"],
    "Jafferabad": ["Jafferabad","Jalna","Badnapur"],
    "Jalna": ["Jalna","Ambad","Badnapur"],
    "Mantha": ["Mantha","Bhokardan","Jalna"],
    "Partur": ["Partur","Jalna","Ghansawangi"],
  },
  "Kolhapur": {
    "Ajra": ["Ajra","Chandgad","Gadhinglaj"],
    "Bavda": ["Bavda","Karvir","Kolhapur"],
    "Bhudargad": ["Bhudargad","Gaganbawda","Radhanagari"],
    "Chandgad": ["Chandgad","Ajra","Gadhinglaj"],
    "Gadhinglaj": ["Gadhinglaj","Ajra","Chandgad"],
    "Hatkanangle": ["Hatkanangle","Ichalkaranji","Shirol"],
    "Kagal": ["Kagal","Karvir","Hatkanangle"],
    "Karvir": ["Kolhapur","Karvir","Kagal","Bavda"],
    "Panhala": ["Panhala","Kolhapur","Shahuwadi"],
    "Radhanagari": ["Radhanagari","Bhudargad","Gaganbawda"],
    "Shahuwadi": ["Shahuwadi","Panhala","Kolhapur"],
    "Shirol": ["Shirol","Hatkanangle","Sangli"],
  },
  "Latur": {
    "Ahmadpur": ["Ahmadpur","Latur","Udgir"],
    "Ausa": ["Ausa","Latur","Nilanga"],
    "Chakur": ["Chakur","Latur","Renapur"],
    "Deoni": ["Deoni","Latur","Jalkot"],
    "Jalkot": ["Jalkot","Latur","Deoni"],
    "Latur": ["Latur","Udgir","Ausa"],
    "Nilanga": ["Nilanga","Ausa","Latur"],
    "Renapur": ["Renapur","Latur","Chakur"],
    "Shirur Anantpal": ["Shirur Anantpal","Latur","Nilanga"],
    "Udgir": ["Udgir","Latur","Ahmadpur"],
  },
  "Nagpur": {
    "Bhiwapur": ["Bhiwapur","Umred","Nagpur"],
    "Hingna": ["Hingna","Nagpur","Kamptee"],
    "Kalmeshwar": ["Kalmeshwar","Savner","Nagpur"],
    "Kamptee": ["Kamptee","Nagpur","Hingna"],
    "Katol": ["Katol","Narkhed","Nagpur"],
    "Kuhi": ["Kuhi","Umred","Bhiwapur"],
    "Mauda": ["Mauda","Parseoni","Nagpur"],
    "Nagpur Rural": ["Nagpur","Butibori","Hingna","Kalmeshwar"],
    "Nagpur Urban": ["Nagpur","Sitabuldi","Dharampeth","Sadar","Civil Lines"],
    "Narkhed": ["Narkhed","Katol","Savner"],
    "Parseoni": ["Parseoni","Mauda","Ramtek"],
    "Ramtek": ["Ramtek","Parseoni","Umred"],
    "Savner": ["Savner","Kalmeshwar","Narkhed"],
    "Umred": ["Umred","Bhiwapur","Kuhi"],
  },
  "Nanded": {
    "Ardhapur": ["Ardhapur","Nanded","Mudkhed"],
    "Bhokar": ["Bhokar","Kinwat","Nanded"],
    "Biloli": ["Biloli","Deglur","Nanded"],
    "Deglur": ["Deglur","Biloli","Nanded"],
    "Dharmabad": ["Dharmabad","Nanded","Biloli"],
    "Hadgaon": ["Hadgaon","Kinwat","Nanded"],
    "Himayatnagar": ["Himayatnagar","Nanded","Mahur"],
    "Kandhar": ["Kandhar","Nanded","Mukhed"],
    "Kinwat": ["Kinwat","Hadgaon","Bhokar"],
    "Loha": ["Loha","Nanded","Mukhed"],
    "Mahur": ["Mahur","Nanded","Himayatnagar"],
    "Mudkhed": ["Mudkhed","Ardhapur","Nanded"],
    "Mukhed": ["Mukhed","Kandhar","Loha"],
    "Naigaon": ["Naigaon","Nanded","Mudkhed"],
    "Nanded": ["Nanded","Ardhapur","Mudkhed"],
    "Umri": ["Umri","Nanded","Ardhapur"],
  },
  "Nandurbar": {
    "Akkalkuwa": ["Akkalkuwa","Nandurbar","Shahada"],
    "Akrani": ["Akrani","Nandurbar","Taloda"],
    "Nandurbar": ["Nandurbar","Shahada","Taloda"],
    "Nawapur": ["Nawapur","Nandurbar","Shahada"],
    "Shahada": ["Shahada","Nandurbar","Taloda"],
    "Taloda": ["Taloda","Nandurbar","Akkalkuwa"],
  },
  "Nashik": {
    "Baglan": ["Baglan","Malegaon","Satana"],
    "Chandwad": ["Chandwad","Nandgaon","Nashik"],
    "Deola": ["Deola","Kalwan","Malegaon"],
    "Dindori": ["Dindori","Nashik","Igatpuri"],
    "Igatpuri": ["Igatpuri","Nashik","Ghoti"],
    "Kalwan": ["Kalwan","Baglan","Malegaon"],
    "Malegaon": ["Malegaon","Baglan","Kalwan"],
    "Nandgaon": ["Nandgaon","Chandwad","Nashik"],
    "Nashik": ["Nashik","Deolali","Sinnar","Trimbakeshwar"],
    "Niphad": ["Niphad","Nashik","Sinnar"],
    "Peint": ["Peint","Igatpuri","Nashik"],
    "Sinnar": ["Sinnar","Niphad","Nashik"],
    "Surgana": ["Surgana","Peint","Kalwan"],
    "Trimbakeshwar": ["Trimbakeshwar","Nashik","Igatpuri"],
    "Yevla": ["Yevla","Niphad","Nashik"],
  },
  "Osmanabad": {
    "Bhum": ["Bhum","Osmanabad","Paranda"],
    "Kallam": ["Kallam","Osmanabad","Tuljapur"],
    "Kalamb": ["Kalamb","Osmanabad","Tuljapur"],
    "Lohara": ["Lohara","Osmanabad","Umarga"],
    "Osmanabad": ["Osmanabad","Tuljapur","Umerga"],
    "Paranda": ["Paranda","Bhum","Osmanabad"],
    "Tuljapur": ["Tuljapur","Osmanabad","Kallam"],
    "Umarga": ["Umarga","Lohara","Osmanabad"],
    "Washi": ["Washi","Osmanabad","Paranda"],
  },
  "Palghar": {
    "Dahanu": ["Dahanu","Talasari","Palghar"],
    "Jawhar": ["Jawhar","Mokhada","Vikramgad"],
    "Mokhada": ["Mokhada","Jawhar","Vikramgad"],
    "Palghar": ["Palghar","Vasai","Wada"],
    "Talasari": ["Talasari","Dahanu","Palghar"],
    "Vasai": ["Vasai","Virar","Nalasopara","Palghar"],
    "Vikramgad": ["Vikramgad","Jawhar","Mokhada"],
    "Wada": ["Wada","Palghar","Bhiwandi"],
  },
  "Parbhani": {
    "Gangakhed": ["Gangakhed","Parbhani","Pathari"],
    "Jintur": ["Jintur","Parbhani","Purna"],
    "Manwath": ["Manwath","Parbhani","Sailu"],
    "Palam": ["Palam","Parbhani","Sonpeth"],
    "Parbhani": ["Parbhani","Purna","Jintur"],
    "Pathri": ["Pathri","Gangakhed","Parbhani"],
    "Purna": ["Purna","Jintur","Parbhani"],
    "Sailu": ["Sailu","Manwath","Parbhani"],
    "Sonpeth": ["Sonpeth","Palam","Parbhani"],
  },
  "Pune": {
    "Ambegaon": ["Ambegaon","Ghodegaon","Manchar","Rajgurunagar"],
    "Baramati": ["Baramati","Phaltan","Indapur","Malegaon"],
    "Bhor": ["Bhor","Velhe","Nasarapur"],
    "Daund": ["Daund","Yavat","Kedgaon","Ranjangaon"],
    "Haveli": ["Pune","Hadapsar","Kharadi","Wagholi","Lohegaon","Uruli Kanchan","Manjari"],
    "Indapur": ["Indapur","Baramati","Bhigwan","Nimgaon Ketki"],
    "Junnar": ["Junnar","Otur","Narayangaon","Alephata"],
    "Khed": ["Rajgurunagar","Chakan","Khed","Shikrapur"],
    "Maval": ["Maval","Vadgaon","Talegaon Dabhade","Dehu Road"],
    "Mulshi": ["Mulshi","Paud","Pirangut","Lavale"],
    "Pune City": ["Pune","Shivajinagar","Kothrud","Pimple Saudagar","Hadapsar"],
    "Purandar": ["Purandar","Saswad","Jejuri","Narayanpur"],
    "Shirur": ["Shirur","Ranjangaon","Shikrapur","Koregaon Bhima"],
    "Velhe": ["Velhe","Bhor","Nasarapur"],
  },
  "Raigad": {
    "Alibag": ["Alibag","Revdanda","Nagaon","Chaul"],
    "Karjat": ["Karjat","Khopoli","Neral","Vangani"],
    "Khalapur": ["Khalapur","Khopoli","Palaspe"],
    "Mahad": ["Mahad","Poladpur","Mangaon"],
    "Mangaon": ["Mangaon","Mahad","Tala"],
    "Mhasla": ["Mhasla","Shriwardhan","Mangaon"],
    "Murud": ["Murud","Alibag","Shriwardhan"],
    "Panvel": ["Panvel","Uran","New Panvel","Kamothe"],
    "Pen": ["Pen","Alibag","Panvel"],
    "Poladpur": ["Poladpur","Mahad","Mangaon"],
    "Roha": ["Roha","Alibag","Pen"],
    "Shriwardhan": ["Shriwardhan","Mhasla","Murud"],
    "Sudhagad": ["Pali","Sudhagad","Pen"],
    "Tala": ["Tala","Mangaon","Shriwardhan"],
    "Uran": ["Uran","Panvel","JNPT"],
  },
  "Ratnagiri": {
    "Chiplun": ["Chiplun","Sangameshwar","Guhagar"],
    "Dapoli": ["Dapoli","Khed","Mandangad"],
    "Guhagar": ["Guhagar","Chiplun","Sangameshwar"],
    "Khed": ["Khed","Dapoli","Ratnagiri"],
    "Lanja": ["Lanja","Rajapur","Ratnagiri"],
    "Mandangad": ["Mandangad","Dapoli","Khed"],
    "Rajapur": ["Rajapur","Lanja","Ratnagiri"],
    "Ratnagiri": ["Ratnagiri","Mirya","Pagdewadi"],
    "Sangameshwar": ["Sangameshwar","Chiplun","Guhagar"],
  },
  "Sangli": {
    "Atpadi": ["Atpadi","Jat","Sangli"],
    "Jat": ["Jat","Atpadi","Sangli"],
    "Kadegaon": ["Kadegaon","Sangli","Walwa"],
    "Kavathemahankal": ["Kavathemahankal","Sangli","Miraj"],
    "Khanapur": ["Khanapur","Vita","Sangli"],
    "Miraj": ["Miraj","Sangli","Kupwad"],
    "Palus": ["Palus","Sangli","Miraj"],
    "Shirala": ["Shirala","Palus","Sangli"],
    "Tasgaon": ["Tasgaon","Sangli","Khanapur"],
    "Walwa": ["Islampur","Walwa","Sangli"],
  },
  "Satara": {
    "Jaoli": ["Medha","Jaoli","Mahabaleshwar"],
    "Karad": ["Karad","Kshetra Mahuli","Umbraj"],
    "Khandala": ["Khandala","Lonand","Satara"],
    "Khatav": ["Khatav","Vaduj","Satara"],
    "Koregaon": ["Koregaon","Satara","Phaltan"],
    "Mahabaleshwar": ["Mahabaleshwar","Panchgani","Wai"],
    "Man": ["Dahiwadi","Man","Satara"],
    "Patan": ["Patan","Karad","Satara"],
    "Phaltan": ["Phaltan","Baramati","Satara"],
    "Satara": ["Satara","Karad","Koregaon"],
    "Wai": ["Wai","Mahabaleshwar","Panchgani"],
  },
  "Sindhudurg": {
    "Devgad": ["Devgad","Kankavli","Kudal"],
    "Dodamarg": ["Dodamarg","Sawantwadi","Kudal"],
    "Kankavli": ["Kankavli","Devgad","Kudal"],
    "Kudal": ["Kudal","Kankavli","Sawantwadi"],
    "Malvan": ["Malvan","Vengurla","Kankavli"],
    "Sawantwadi": ["Sawantwadi","Kudal","Dodamarg"],
    "Vaibhavwadi": ["Vaibhavwadi","Kankavli","Kudal"],
    "Vengurla": ["Vengurla","Malvan","Sawantwadi"],
  },
  "Solapur": {
    "Akkalkot": ["Akkalkot","Solapur","Mangalwedha"],
    "Barshi": ["Barshi","Madha","Solapur"],
    "Karmala": ["Karmala","Madha","Solapur"],
    "Madha": ["Madha","Barshi","Karmala"],
    "Malshiras": ["Malshiras","Pandharpur","Sangola"],
    "Mangalwedha": ["Mangalwedha","Pandharpur","Solapur"],
    "Mohol": ["Mohol","Solapur","Akkalkot"],
    "North Solapur": ["Solapur","Akluj","Barshi"],
    "Pandharpur": ["Pandharpur","Malshiras","Mangalwedha"],
    "Sangola": ["Sangola","Malshiras","Pandharpur"],
    "South Solapur": ["Solapur","Akkalkot","Mohol"],
  },
  "Thane": {
    "Ambarnath": ["Ambarnath","Badlapur","Ulhasnagar"],
    "Bhiwandi": ["Bhiwandi","Kalyan","Wada"],
    "Kalyan": ["Kalyan","Dombivli","Titwala","Ambivli"],
    "Murbad": ["Murbad","Kalyan","Shahapur"],
    "Shahapur": ["Shahapur","Murbad","Kalyan"],
    "Thane": ["Thane","Mumbra","Diva","Kalwa"],
    "Ulhasnagar": ["Ulhasnagar","Ambarnath","Badlapur"],
  },
  "Wardha": {
    "Arvi": ["Arvi","Wardha","Karanja"],
    "Ashti": ["Ashti","Wardha","Seloo"],
    "Deoli": ["Deoli","Wardha","Hinganghat"],
    "Hinganghat": ["Hinganghat","Wardha","Deoli"],
    "Karanja": ["Karanja","Washim","Wardha"],
    "Samudrapur": ["Samudrapur","Wardha","Hinganghat"],
    "Seloo": ["Seloo","Wardha","Ashti"],
    "Wardha": ["Wardha","Hinganghat","Arvi"],
  },
  "Washim": {
    "Karanja": ["Karanja","Washim","Akola"],
    "Malegaon": ["Malegaon","Washim","Risod"],
    "Mangrulpir": ["Mangrulpir","Washim","Risod"],
    "Manora": ["Manora","Washim","Risod"],
    "Risod": ["Risod","Washim","Mangrulpir"],
    "Washim": ["Washim","Risod","Karanja"],
  },
  "Yavatmal": {
    "Arni": ["Arni","Yavatmal","Pusad"],
    "Babulgaon": ["Babulgaon","Yavatmal","Darwha"],
    "Darwha": ["Darwha","Yavatmal","Babulgaon"],
    "Digras": ["Digras","Pusad","Yavatmal"],
    "Ghatanji": ["Ghatanji","Yavatmal","Kelapur"],
    "Kalamb": ["Kalamb","Yavatmal","Darwha"],
    "Kelapur": ["Kelapur","Pandharkawada","Ghatanji"],
    "Mahagaon": ["Mahagaon","Yavatmal","Darwha"],
    "Maregaon": ["Maregaon","Yavatmal","Pusad"],
    "Ner": ["Ner","Pusad","Yavatmal"],
    "Pusad": ["Pusad","Digras","Ner"],
    "Ralegaon": ["Ralegaon","Yavatmal","Darwha"],
    "Umarkhed": ["Umarkhed","Pusad","Yavatmal"],
    "Wani": ["Wani","Yavatmal","Pusad"],
    "Yavatmal": ["Yavatmal","Wani","Pusad"],
    "Zari Jamani": ["Zari Jamani","Yavatmal","Kelapur"],
  },
};

export const getVillages = (district, taluka) =>
  villageData[district]?.[taluka] || [];

export default villageData;
