// Privacy Policy — verbatim content (do not edit wording)
// block types: h1 | sub | meta | h2 | h3 | p | ul | quote

export const privacyMr = [
    { t: "h1", x: "गोपनीयता धोरण" },
    { t: "sub", x: "गाव तिथे उद्योजक पोर्टल" },
    { t: "meta", x: "प्रभावी दिनांक: १ जुलै २०२६" },
    { t: "meta", x: "शेवटचे अद्यतन: २६ सप्टेंबर २०२६" },

    { t: "h2", x: "1. प्रस्तावना" },
    { t: "p", x: "गाव तिथे उद्योजक पोर्टल (“पोर्टल”) हे गाव तिथे उद्योजक इन्क्यूबेशन कौन्सिल, (“GTUIC”) ही कंपनी कायदा २०१३ च्या Section 8 (कलम ८) अंतर्गत नोंदणीकृत संस्था (Non-profit Organization) यांच्या मालकीचे व नियंत्रणाखालील अधिकृत डिजिटल पोर्टल आहे." },
    { t: "p", x: "हे पोर्टल गाव तिथे उद्योजक अभियान (“अभियान”)महाराष्ट्र राज्यात राबविण्यासाठी GTUICद्वारे महाराष्ट्र चेंबर ऑफ कॉमर्स, इंडस्ट्री अँड अग्रीकल्चर (MACCIA) यांच्या संयुक्त विद्यमाने वापरण्यात येत आहे." },
    { t: "p", x: "या गोपनीयता धोरण चा उद्देश पोर्टलवर येणाऱ्या अर्जदारांकडून/वापरकर्त्यांकडून संकलित होणारी वैयक्तिक, व्यावसायिक, आर्थिक व इतर आवश्यक माहिती कशा प्रकारे संकलित, वापरली, साठवली, प्रक्रिया व आवश्यकतेनुसार शेअर केली जाऊ शकते, याबाबत स्पष्ट माहिती देणे हा आहे." },
    { t: "p", x: "पोर्टलवर नोंदणी करणे, अर्ज सादर करणे, माहिती भरणे, कागदपत्रे अपलोड करणे किंवा पोर्टलचा संबंधित सेवा/सुविधांसाठी वापर करणे याचा अर्थ अर्जदाराने या गोपनीयता धोरण मधील तरतुदी वाचल्या असून त्या समजून घेतल्या आहेत असे मानले जाईल." },

    { t: "h2", x: "2. गाव तिथे उद्योजक अभियानाचा उद्देश" },
    { t: "p", x: "गाव तिथे उद्योजक अभियानाचा मुख्य उद्देश महाराष्ट्रातील ग्रामीण भागातील इच्छुक व्यक्तींना उद्योजकतेसाठी आवश्यक मार्गदर्शन, प्रशिक्षण, सहाय्य व संधी उपलब्ध करून देणे हा आहे." },
    { t: "p", x: "अभियानाच्या माध्यमातून, उपलब्ध संसाधने व संबंधित संस्थांच्या सहकार्याच्या आधारे अर्जदारांना खालील बाबींमध्ये सहाय्य करण्याचा प्रयत्न केला जाऊ शकतो:" },
    { t: "ul", x: [
        "उद्योजकतेबाबत मार्गदर्शन;",
        "योग्य व्यवसाय/उद्योगाची निवड करण्यासाठी मार्गदर्शन;",
        "व्यवसाय कल्पना विकसित करण्यासाठी मार्गदर्शन;",
        "उद्योजकता प्रशिक्षण व कौशल्यविकास;",
        "व्यवसाय नियोजन व प्रकल्प अहवाल तयार करण्यासाठी मार्गदर्शन;",
        "शासकीय योजना व संबंधित सुविधांची माहिती;",
        "शासकीय योजना, अनुदान, कर्ज किंवा इतर आर्थिक सहाय्यासाठी मार्गदर्शन व सहकार्य;",
        "बँका, वित्तीय संस्था व इतर निधीपुरवठा संस्थांशी आवश्यक तेथे संपर्क व समन्वय;",
        "उत्पादन व सेवांसाठी बाजारपेठ व बाजारपेठीय संधी शोधण्यासाठी सहाय्य;",
        "उद्योग, व्यापार, बाजारपेठ, तज्ज्ञ, मार्गदर्शक व संबंधित संस्थांशी संपर्क;",
        "प्रशिक्षण, कार्यशाळा, परिसंवाद, उद्योजकता कार्यक्रम व इतर उपक्रमांमध्ये सहभागी होण्यासाठी सुविधा; आणि",
        "अभियानाच्या उद्दिष्टांशी संबंधित इतर सहाय्य.",
    ] },

    { t: "h2", x: "3. पोर्टलद्वारे कोणती माहिती संकलित केली जाऊ शकते?" },
    { t: "p", x: "अर्जदाराने अभियानामध्ये सहभागी होण्यासाठी किंवा संबंधित सहाय्य मिळविण्यासाठी आवश्यकतेनुसार खालील प्रकारची माहिती स्वेच्छेने उपलब्ध करून दिली जाऊ शकते." },

    { t: "h3", x: "3.1 वैयक्तिक माहिती" },
    { t: "ul", x: [
        "पूर्ण नाव;",
        "मोबाईल क्रमांक;",
        "ई-मेल पत्ता;",
        "जन्मतारीख/वय;",
        "लिंग, आवश्यक असल्यास;",
        "राहण्याचा पत्ता;",
        "गाव;",
        "तालुका;",
        "जिल्हा;",
        "राज्य;",
        "शैक्षणिक माहिती;",
        "व्यवसाय/नोकरीची माहिती;",
        "अनुभव;",
        "कौशल्ये व इतर संबंधित माहिती.",
    ] },

    { t: "h3", x: "3.2 उद्योजकता व व्यवसायाशी संबंधित माहिती" },
    { t: "p", x: "अर्जदाराच्या प्रस्तावित किंवा विद्यमान व्यवसायाच्या स्वरूपानुसार:" },
    { t: "ul", x: [
        "व्यवसायाचे नाव;",
        "व्यवसायाचा प्रकार;",
        "व्यवसायाचे स्वरूप;",
        "प्रस्तावित व्यवसाय कल्पना;",
        "व्यवसायाचे ठिकाण;",
        "विद्यमान व्यवसायाची माहिती;",
        "उत्पादनांची माहिती;",
        "सेवांची माहिती;",
        "व्यवसायाचा अनुभव;",
        "अपेक्षित गुंतवणूक;",
        "अपेक्षित निधीची आवश्यकता;",
        "व्यवसायाचा अंदाजित विस्तार;",
        "रोजगारनिर्मितीची क्षमता;",
        "बाजारपेठेशी संबंधित माहिती;",
        "व्यवसाय नोंदणीची माहिती; आणि",
        "इतर आवश्यक व्यवसायविषयक माहिती.",
    ] },

    { t: "h3", x: "3.3 आर्थिक माहिती" },
    { t: "p", x: "अभियानाच्या उद्देशाने किंवा आर्थिक सहाय्य/शासकीय योजनांसाठी मार्गदर्शन व सहकार्य करण्यासाठी आवश्यक असल्यास:" },
    { t: "ul", x: [
        "प्रस्तावित प्रकल्पाची किंमत;",
        "अपेक्षित गुंतवणूक;",
        "निधीची आवश्यकता;",
        "विद्यमान व्यवसायाची आर्थिक माहिती;",
        "बँक/वित्तीय संस्थेशी संबंधित माहिती;",
        "कर्जासंबंधी माहिती;",
        "क्रेडिट/आर्थिक पात्रतेशी संबंधित माहिती, लागू असल्यास;",
        "शासकीय योजना किंवा आर्थिक सहाय्यासाठी आवश्यक इतर माहिती.",
    ] },

    { t: "h3", x: "3.4 कागदपत्रे" },
    { t: "p", x: "अर्जाच्या स्वरूपानुसार अर्जदाराकडून आवश्यक कागदपत्रे मागविली जाऊ शकतात, जसे की:" },
    { t: "ul", x: [
        "ओळखपत्र;",
        "पत्त्याचा पुरावा;",
        "व्यवसाय नोंदणी कागदपत्रे;",
        "शैक्षणिक/प्रशिक्षण प्रमाणपत्रे;",
        "परवाने व प्रमाणपत्रे;",
        "प्रकल्प अहवाल;",
        "आर्थिक कागदपत्रे;",
        "बँकसंबंधित कागदपत्रे;",
        "शासकीय योजनांसाठी आवश्यक कागदपत्रे; आणि",
        "संबंधित अर्जासाठी आवश्यक इतर कागदपत्रे.",
    ] },

    { t: "h2", x: "4. माहिती अर्जदाराने स्वेच्छेने दिलेली आहे" },
    { t: "p", x: "पोर्टलवर अर्जदाराने स्वतः भरलेली माहिती, अपलोड केलेली कागदपत्रे किंवा इतर स्वरूपात उपलब्ध करून दिलेली माहिती ही अर्जदाराने स्वेच्छेने व स्वतःच्या जबाबदारीवर उपलब्ध करून दिली आहे, असे मानले जाईल." },
    { t: "p", x: "अर्जदाराने सादर केलेली माहिती:" },
    { t: "ul", x: [
        "खरी व अचूक;",
        "पूर्ण;",
        "अद्ययावत;",
        "कायदेशीररीत्या उपलब्ध करून दिलेली; आणि",
        "संबंधित अर्जाच्या उद्देशासाठी योग्य",
    ] },
    { t: "p", x: "असल्याची जबाबदारी पूर्णपणे अर्जदाराची राहील." },
    { t: "p", x: "चुकीची, अपूर्ण, खोटी, दिशाभूल करणारी किंवा बनावट माहिती अथवा कागदपत्रे सादर केल्यामुळे होणाऱ्या परिणामांसाठी GTUIC, MACCIA किंवा अभियानाशी संबंधित इतर संस्था/व्यक्ती जबाबदार राहणार नाहीत." },

    { t: "h2", x: "5. माहिती संकलित करण्याचा उद्देश" },
    { t: "p", x: "अर्जदाराकडून संकलित केलेली माहिती खालील उद्देशांसाठी वापरली व प्रक्रिया केली जाऊ शकते:" },
    { t: "ul", x: [
        "पोर्टलवर अर्जदाराची नोंदणी करणे;",
        "अभियानासाठी अर्ज स्वीकारणे व त्यावर प्रक्रिया करणे;",
        "अर्जदाराची उद्योजकता क्षमता, गरज व व्यवसायाची माहिती समजून घेणे;",
        "योग्य उद्योग/व्यवसाय निवडण्यासाठी मार्गदर्शन करणे;",
        "प्रशिक्षण, मार्गदर्शन, mentoring व incubation सुविधा उपलब्ध करून देणे;",
        "व्यवसाय कल्पना व प्रकल्प विकसित करण्यासाठी सहाय्य करणे;",
        "शासकीय योजना व सुविधांसाठी मार्गदर्शन करणे;",
        "बँका, वित्तीय संस्था व इतर संस्थांमार्फत आर्थिक सहाय्य मिळविण्यासाठी आवश्यक मार्गदर्शन व सहकार्य करणे;",
        "उत्पादन व सेवांसाठी बाजारपेठीय संधी उपलब्ध करून देण्यासाठी सहाय्य करणे;",
        "अर्जदारांना संबंधित तज्ज्ञ, प्रशिक्षक, mentors, उद्योग संस्था व भागीदार संस्थांशी जोडणे;",
        "अभियानातील प्रशिक्षण, कार्यशाळा, कार्यक्रम व उपक्रमांचे नियोजन करणे;",
        "अर्जदारांशी अभियानासंदर्भात आवश्यक संवाद साधणे;",
        "अभियानाच्या कार्यक्षमतेचे मूल्यमापन व सुधारणा करणे;",
        "सांख्यिकीय, संशोधनात्मक किंवा विश्लेषणात्मक स्वरूपातील माहिती तयार करणे;",
        "फसवणूक, गैरवापर किंवा अनधिकृत वापर रोखणे;",
        "कायदेशीर, प्रशासकीय किंवा नियामक आवश्यकता पूर्ण करणे; आणि",
        "अभियानाच्या उद्दिष्टांशी संबंधित इतर कायदेशीर व आवश्यक कारणांसाठी माहिती प्रक्रिया करणे.",
    ] },

    { t: "h2", x: "6. माहिती कोणासोबत शेअर केली जाऊ शकते?" },
    { t: "p", x: "अभियानाच्या उद्दिष्टांची पूर्तता करण्यासाठी किंवा अर्जदाराने मागितलेले मार्गदर्शन/सहाय्य उपलब्ध करून देण्यासाठी अर्जदाराची संबंधित माहिती आवश्यकतेनुसार खालील संस्थांसोबत शेअर केली जाऊ शकते:" },
    { t: "ul", x: [
        "गाव तिथे उद्योजक इन्क्यूबेशन कौन्सिल (GTUIC);",
        "महाराष्ट्र चेंबर ऑफ कॉमर्स, इंडस्ट्री अँड अग्रीकल्चर (MACCIA);",
        "संबंधित केंद्र/राज्य शासकीय विभाग;",
        "स्थानिक स्वराज्य संस्था किंवा संबंधित शासकीय यंत्रणा;",
        "बँका;",
        "वित्तीय संस्था;",
        "NBFCs किंवा इतर अधिकृत वित्तीय संस्था;",
        "शासकीय योजना राबविणाऱ्या संस्था;",
        "उद्योग संघटना;",
        "प्रशिक्षण व शैक्षणिक संस्था;",
        "incubation व entrepreneurship support organisations;",
        "mentors, consultants, trainers व subject-matter experts;",
        "अभियानासाठी अधिकृत भागीदार संस्था;",
        "पोर्टलच्या hosting, technology, security, communication किंवा इतर तांत्रिक सेवा देणारे अधिकृत service providers; आणि",
        "अभियानाच्या उद्देशासाठी किंवा अर्जदाराने मागितलेल्या विशिष्ट सहाय्यासाठी आवश्यक असलेल्या इतर अधिकृत संस्था/व्यक्ती.",
    ] },
    { t: "p", x: "माहितीचे असे आदान-प्रदान अभियानाच्या उद्देशाशी संबंधित, आवश्यक आणि लागू कायद्यांच्या अधीन राहील." },

    { t: "h2", x: "7. वित्तीय संस्था व शासकीय विभागांसोबत माहिती शेअर करण्यास संमती" },
    { t: "p", x: "अर्जदाराने कर्ज, आर्थिक सहाय्य, शासकीय योजना, अनुदान, subsidy, बाजारपेठीय सहाय्य किंवा इतर सुविधा मिळविण्यासाठी अर्ज केल्यास, संबंधित प्रक्रिया पूर्ण करण्यासाठी अर्जदाराची आवश्यक माहिती संबंधित:" },
    { t: "ul", x: [
        "शासकीय विभाग;",
        "बँक;",
        "वित्तीय संस्था;",
        "योजना अंमलबजावणी संस्था; किंवा",
        "संबंधित अधिकृत संस्था",
    ] },
    { t: "p", x: "यांच्यासोबत शेअर करणे आवश्यक असू शकते." },
    { t: "p", x: "पोर्टलवर अर्ज सादर करताना अर्जदाराने अशी माहिती शेअर करण्यास लागू कायद्यानुसार आवश्यक त्या प्रमाणात संमती/परवानगी दिली आहे, असे मानले जाईल." },

    { t: "h2", x: "8. माहितीच्या सुरक्षिततेबाबत" },
    { t: "p", x: "GTUIC अर्जदाराची माहिती अनधिकृत प्रवेश, गैरवापर, बदल, अनधिकृत प्रकटीकरण, नुकसान किंवा नष्ट होण्यापासून सुरक्षित ठेवण्यासाठी वाजवी तांत्रिक व प्रशासकीय उपाययोजना करण्याचा प्रयत्न करेल." },
    { t: "p", x: "यामध्ये आवश्यकतेनुसार:" },
    { t: "ul", x: [
        "access controls;",
        "authentication;",
        "secure hosting;",
        "data security measures;",
        "authorised access;",
        "monitoring;",
        "backup व recovery व्यवस्था; आणि",
        "इतर योग्य सुरक्षा उपाय",
    ] },
    { t: "p", x: "यांचा समावेश असू शकतो." },
    { t: "p", x: "तथापि, इंटरनेटवर आधारित कोणतीही प्रणाली पूर्णपणे सुरक्षित असल्याची हमी देता येत नाही. त्यामुळे कोणत्याही अनपेक्षित cyber attack, technical failure, unauthorised intrusion किंवा इतर अनियंत्रित घटनेमुळे उद्भवणाऱ्या प्रत्येक संभाव्य जोखमीची पूर्णपणे हमी देणे शक्य नाही." },

    { t: "h2", x: "9. माहितीचा साठवण कालावधी" },
    { t: "p", x: "अर्जदाराची माहिती अभियानाच्या कार्यवाहीसाठी, नोंदवही व प्रशासकीय कारणांसाठी, प्रशिक्षण/मार्गदर्शनासाठी, शासकीय योजना किंवा वित्तीय सहाय्याच्या प्रक्रियेसाठी, कायदेशीर व नियामक आवश्यकतांसाठी किंवा इतर संबंधित वैध कारणांसाठी आवश्यक असेपर्यंत साठवली जाऊ शकते." },
    { t: "p", x: "माहितीची आवश्यकता संपल्यानंतर लागू कायदे, नियम व संस्थेच्या data-retention requirements नुसार ती माहिती delete, anonymise, archive किंवा अन्य पद्धतीने हाताळली जाऊ शकते." },

    { t: "h2", x: "10. तृतीय पक्षांकडे माहिती दिल्यानंतरची जबाबदारी" },
    { t: "p", x: "अर्जदाराच्या विनंतीनुसार किंवा अभियानाच्या उद्देशासाठी एखादी माहिती संबंधित शासकीय विभाग, बँक, वित्तीय संस्था, partner organisation किंवा इतर authorised third party यांच्याकडे शेअर केल्यानंतर त्या संस्थेकडून त्या माहितीवर होणाऱ्या स्वतंत्र processing साठी त्या संस्थेचे स्वतःचे नियम, अटी व गोपनीयता धोरण लागू होऊ शकतात." },
    { t: "p", x: "अशा तृतीय पक्षांच्या स्वतंत्र privacy practices साठी, त्यांच्या नियंत्रणाबाहेरील बाबींमध्ये GTUIC किंवा MACCIA जबाबदार राहणार नाहीत." },

    { t: "h2", x: "11. शासकीय योजना, कर्ज व आर्थिक सहाय्याबाबत महत्त्वाची सूचना" },
    { t: "p", x: "अभियानामार्फत अर्जदारांना शासकीय योजना, कर्ज, अनुदान, subsidy, वित्तीय सहाय्य किंवा इतर आर्थिक सुविधा मिळविण्यासाठी मार्गदर्शन व सहकार्य केले जाऊ शकते." },
    { t: "p", x: "मात्र:" },
    { t: "ul", x: [
        "पोर्टलवर नोंदणी केल्याने कोणत्याही योजनेचा लाभ निश्चित होत नाही;",
        "कोणत्याही कर्जाची मंजुरी हमखास मिळेल असे नाही;",
        "कोणतेही अनुदान, subsidy किंवा आर्थिक सहाय्य मिळण्याची हमी दिली जात नाही;",
        "पात्रता संबंधित शासकीय विभाग किंवा वित्तीय संस्थेच्या नियमांनुसार ठरते;",
        "अंतिम निर्णय संबंधित शासकीय विभाग, बँक किंवा वित्तीय संस्थेचा राहील; आणि",
        "आवश्यक अतिरिक्त कागदपत्रे किंवा माहिती अर्जदाराला थेट संबंधित संस्थेकडे द्यावी लागू शकते.",
    ] },

    { t: "h2", x: "12. बाजारपेठ व व्यवसाय संधींबाबत सूचना" },
    { t: "p", x: "अभियानाच्या माध्यमातून अर्जदारांच्या उत्पादनांना किंवा सेवांना बाजारपेठ, ग्राहक, व्यापारी, उद्योग संस्था किंवा इतर व्यावसायिक संधी उपलब्ध करून देण्यासाठी प्रयत्न केले जाऊ शकतात." },
    { t: "p", x: "तथापि, कोणतीही विशिष्ट विक्री, ऑर्डर, ग्राहक, व्यापार करार, गुंतवणूक, व्यवसाय भागीदारी, उत्पन्न किंवा नफा मिळण्याची हमी अभियान किंवा GTUIC देत नाही." },

    { t: "h2", x: "13. अर्जदाराची जबाबदारी" },
    { t: "p", x: "पोर्टलचा वापर करून अर्ज सादर करताना अर्जदार:" },
    { t: "ul", x: [
        "स्वतःची खरी व अचूक माहिती देईल;",
        "आवश्यक कागदपत्रे योग्य व वैध स्वरूपात देईल;",
        "चुकीची, खोटी किंवा दिशाभूल करणारी माहिती देणार नाही;",
        "दुसऱ्या व्यक्तीची माहिती तिची कायदेशीर परवानगी/अधिकार नसताना देणार नाही;",
        "आपल्या login credentials ची सुरक्षितता राखेल;",
        "माहितीमध्ये बदल झाल्यास आवश्यक तेथे ती अद्ययावत करेल;",
        "अभियान व पोर्टलचा वापर लागू कायद्यांच्या अधीन राहून करेल; आणि",
        "पोर्टलचा गैरवापर, फसवणूक किंवा अनधिकृत प्रवेश करण्याचा प्रयत्न करणार नाही.",
    ] },

    { t: "h2", x: "14. अर्जदाराने दिलेल्या माहितीची सत्यता" },
    { t: "p", x: "पोर्टलवर अर्जदाराने दिलेल्या माहितीची सत्यता, अचूकता, पूर्णता आणि प्रामाणिकपणाची सर्वस्वी जबाबदारी अर्जदाराची राहील." },
    { t: "p", x: "GTUIC, MACCIA किंवा अभियानाशी संबंधित संस्था/व्यक्तींनी अर्जदाराच्या माहितीवर आधारित मार्गदर्शन केले असल्यास, अर्जदाराने दिलेली चुकीची किंवा अपूर्ण माहिती त्यातून उद्भवलेल्या परिणामांसाठी संबंधित संस्था किंवा व्यक्तींना जबाबदार धरले जाणार नाही." },
    { t: "p", x: "आवश्यकतेनुसार माहिती किंवा कागदपत्रांची पडताळणी करण्याचा अधिकार GTUICकडे राहील." },

    { t: "h2", x: "15. पोर्टलवरील माहितीचा वापर" },
    { t: "p", x: "पोर्टलवर उपलब्ध करून दिलेली सार्वजनिक माहिती ही अभियानाविषयी माहिती व मार्गदर्शनासाठी आहे." },
    { t: "p", x: "पोर्टलवरील माहितीच्या आधारे कोणताही अर्जदार व्यवसाय, आर्थिक गुंतवणूक, कर्ज, योजना किंवा इतर निर्णय घेत असल्यास त्याने आवश्यकतेनुसार संबंधित अधिकृत विभाग, वित्तीय संस्था किंवा तज्ज्ञांकडून स्वतंत्र पडताळणी करावी." },

    { t: "h2", x: "16. Cookies व Technical Information" },
    { t: "p", x: "पोर्टलच्या कार्यक्षमतेसाठी आवश्यकतेनुसार cookies, session technologies, analytics tools किंवा तत्सम तंत्रज्ञानाचा वापर केला जाऊ शकतो." },
    { t: "p", x: "यांचा वापर:" },
    { t: "ul", x: [
        "login/session व्यवस्थापन;",
        "सुरक्षा;",
        "पोर्टलची कार्यक्षमता;",
        "technical समस्या ओळखणे;",
        "user experience सुधारणे; आणि",
        "aggregated usage analysis",
    ] },
    { t: "p", x: "यासाठी केला जाऊ शकतो." },

    { t: "h2", x: "17. तृतीय पक्षांच्या वेबसाइट्स" },
    { t: "p", x: "पोर्टलवर शासकीय विभाग, बँका, वित्तीय संस्था, partner organisations किंवा इतर तृतीय पक्षांच्या वेबसाइट्सचे links असू शकतात." },
    { t: "p", x: "अशा वेबसाइटवर प्रवेश केल्यानंतर त्या संस्थेची स्वतंत्र गोपनीयता धोरण व Terms लागू होऊ शकतात." },
    { t: "p", x: "त्या वेबसाइट्सच्या content, security किंवा privacy practices वर GTUICचे नियंत्रण नसल्यामुळे त्यासाठी GTUIC जबाबदार राहणार नाही." },

    { t: "h2", x: "18. अभियानाशी संबंधित संवाद" },
    { t: "p", x: "पोर्टलवर नोंदणी किंवा अर्ज केल्यानंतर अर्जदाराशी खालील बाबींशी संबंधित संवाद साधला जाऊ शकतो:" },
    { t: "ul", x: [
        "अर्जाची स्थिती;",
        "प्रशिक्षण;",
        "कार्यशाळा;",
        "उद्योजकता कार्यक्रम;",
        "mentoring/incubation;",
        "शासकीय योजना;",
        "वित्तीय सहाय्याच्या संधी;",
        "बाजारपेठीय संधी;",
        "अभियानातील उपक्रम; आणि",
        "अभियानाच्या उद्देशाशी थेट संबंधित इतर माहिती.",
    ] },
    { t: "p", x: "लागू कायद्यानुसार आवश्यक असल्यास स्वतंत्र consent किंवा opt-out सुविधा उपलब्ध करून दिली जाऊ शकते." },

    { t: "h2", x: "19. Privacy Rights व Grievance Redressal" },
    { t: "p", x: "लागू कायद्यानुसार अर्जदाराला त्याच्या वैयक्तिक माहितीच्या processing संदर्भात उपलब्ध असलेले अधिकार वापरण्याची सुविधा दिली जाईल." },
    { t: "p", x: "यामध्ये लागू परिस्थितीनुसार:" },
    { t: "ul", x: [
        "स्वतःच्या माहितीच्या processing बाबत माहिती मागणे;",
        "चुकीची माहिती दुरुस्त करण्याची विनंती करणे;",
        "आवश्यकतेनुसार माहिती अद्ययावत करण्याची विनंती करणे;",
        "लागू कायद्यानुसार माहिती delete करण्याची विनंती करणे;",
        "consent-based processing बाबत consent मागे घेण्याची विनंती करणे; आणि",
        "privacy/data processing बाबत grievance नोंदवणे",
    ] },
    { t: "p", x: "यांचा समावेश असू शकतो." },
    { t: "p", x: "अशा अधिकारांचा वापर लागू कायदे, नियम आणि संबंधित परिस्थितीनुसार केला जाईल." },
    { t: "p", x: "Privacy / Grievance Officer: Rameshwar Pawar\nDesignation: President, Udyog Vichar Manch\nEmail: gtuincubation@gmail.com\nPhone: +91 88308 23679\nAddress: GAON TITHE UDYOJAK INCUBATION COUNCIL (GTUIC), 12, PLOT-12/14, ORICON HO,KAKUSHROO DUBASH MARG, MUMBAI, MAHARASHTRA, 400001" },
    { t: "p", x: "लागू कायद्याने अनिवार्यपणे उपलब्ध करून दिलेला कोणताही अधिकार किंवा उपाय या गोपनीयता धोरण मुळे प्रतिबंधित केला जाणार नाही." },

    { t: "h2", x: "20. जबाबदारीची मर्यादा" },
    { t: "p", x: "गाव तिथे उद्योजक अभियान हे अर्जदारांना उद्योजकतेसाठी मार्गदर्शन, प्रशिक्षण, incubation, facilitation आणि विविध संस्थांशी जोडण्याचा प्रयत्न करणारे अभियान आहे." },
    { t: "p", x: "पोर्टलवर नोंदणी किंवा अर्ज केल्यामुळे खालीलपैकी कोणत्याही बाबीची हमी मिळत नाही:" },
    { t: "ul", x: [
        "व्यवसाय सुरू होणे;",
        "व्यवसायाचे यश;",
        "रोजगार;",
        "सरकारी योजनेचा लाभ;",
        "अनुदान किंवा subsidy;",
        "कर्ज मंजुरी;",
        "गुंतवणूक;",
        "ग्राहक किंवा बाजारपेठ;",
        "व्यवसाय भागीदारी;",
        "विक्री किंवा ऑर्डर;",
        "उत्पन्न किंवा नफा.",
    ] },
    { t: "p", x: "अशा बाबींचा अंतिम निर्णय संबंधित शासकीय विभाग, बँक, वित्तीय संस्था, ग्राहक, व्यापारी, भागीदार संस्था किंवा इतर संबंधित तृतीय पक्ष घेतील." },

    { t: "h2", x: "21. माहिती व संमतीबाबत अर्जदाराची घोषणा" },
    { t: "p", x: "पोर्टलवर अर्ज सादर करून अर्जदार खालील बाबी मान्य करतो:" },
    { t: "p", x: "(a) त्याने पोर्टलवर दिलेली माहिती स्वतःच्या इच्छेने व स्वतःच्या जबाबदारीवर दिली आहे." },
    { t: "p", x: "(b) त्याने दिलेली माहिती त्याच्या माहितीनुसार खरी, अचूक व पूर्ण आहे." },
    { t: "p", x: "(c) त्याला समजते की अभियानाच्या उद्देशानुसार त्याची आवश्यक माहिती GTUIC, MACCIA, संबंधित शासकीय विभाग, बँका, वित्तीय संस्था, योजना अंमलबजावणी संस्था, partner organisations, mentors, trainers व इतर authorised entities यांच्यासोबत शेअर केली जाऊ शकते." },
    { t: "p", x: "(d) त्याला समजते की संबंधित शासकीय योजना, कर्ज किंवा वित्तीय सहाय्यासाठी त्याची माहिती संबंधित संस्था/विभागाकडे देणे आवश्यक असू शकते." },
    { t: "p", x: "(e) त्याने दिलेल्या चुकीच्या, खोट्या, अपूर्ण किंवा दिशाभूल करणाऱ्या माहितीमुळे उद्भवणाऱ्या परिणामांची जबाबदारी त्याची स्वतःची राहील." },
    { t: "p", x: "(f) त्याला समजते की पोर्टलवर अर्ज करणे किंवा अभियानात सहभागी होणे हे कोणत्याही आर्थिक लाभ, कर्ज, अनुदान, subsidy, व्यवसाय संधी किंवा इतर परिणामाची हमी नाही." },
    { t: "p", x: "(g) तो या गोपनीयता धोरण मधील अटी वाचून व समजून पोर्टलवर अर्ज करीत आहे." },

    { t: "h2", x: "22. तक्रार, अपील व कायदेशीर अधिकार" },
    { t: "p", x: "अर्जदाराने पोर्टलवर स्वतःहून व स्वेच्छेने माहिती उपलब्ध करून दिल्याने, त्या माहितीच्या सत्यता व अचूकतेची प्राथमिक जबाबदारी अर्जदाराची राहील." },
    { t: "p", x: "अभियानाच्या कार्यवाहीदरम्यान GTUIC, MACCIA किंवा त्यांच्या अधिकृत प्रतिनिधींनी अर्जदाराने उपलब्ध करून दिलेल्या माहितीच्या आधारे केलेले मार्गदर्शन, प्रक्रिया किंवा facilitation हे उपलब्ध माहिती व संबंधित संस्थांच्या नियमांवर आधारित असू शकते." },
    { t: "p", x: "त्यामुळे अर्जदाराने चुकीची, अपूर्ण किंवा दिशाभूल करणारी माहिती दिल्यामुळे निर्माण झालेल्या परिणामांसाठी GTUIC, MACCIA किंवा अभियानाशी संबंधित संस्था/व्यक्तींवर जबाबदारी निश्चित करता येणार नाही." },
    { t: "p", x: "तथापि, लागू कायद्याने उपलब्ध करून दिलेले वैधानिक अधिकार, data-protection rights, grievance mechanisms किंवा न्यायालयीन/कायदेशीर उपाय या गोपनीयता धोरण मुळे रद्द किंवा प्रतिबंधित केले जाणार नाहीत." },

    { t: "h2", x: "23. गोपनीयता धोरणामध्ये बदल" },
    { t: "p", x: "GTUIC आवश्यकतेनुसार या गोपनीयता धोरण मध्ये बदल करू शकते." },
    { t: "p", x: "बदल करण्याची कारणे यामध्ये असू शकतात:" },
    { t: "ul", x: [
        "कायद्यातील बदल;",
        "शासकीय किंवा नियामक निर्देश;",
        "अभियानाच्या स्वरूपातील बदल;",
        "पोर्टलच्या functionality मधील बदल;",
        "data-processing पद्धतीतील बदल; किंवा",
        "privacy व security practices मधील सुधारणा.",
    ] },
    { t: "p", x: "सुधारित गोपनीयता धोरण पोर्टलवर प्रकाशित केली जाईल आणि त्यावर “Last Updated” तारीख नमूद केली जाईल." },

    { t: "h2", x: "24. लागू कायदा" },
    { t: "p", x: "ही गोपनीयता धोरण भारतातील लागू कायदे व नियमांच्या अधीन राहील." },
    { t: "p", x: "वैयक्तिक डेटाच्या processing बाबत लागू असलेल्या data-protection कायदे व नियमांनुसार अर्जदाराचे अधिकार, GTUICच्या जबाबदाऱ्या आणि संबंधित प्रक्रिया निश्चित केल्या जातील." },
    { t: "p", x: "Digital Personal Data Protection Act, 2023 आणि त्याअंतर्गत अधिसूचित नियम लागू होण्याच्या संबंधित टप्प्यानुसार त्यातील लागू तरतुदींचे पालन केले जाईल. सध्याच्या अधिसूचित DPDP Rules, 2025 मध्ये काही तरतुदी टप्प्याटप्प्याने लागू होण्याची तरतूद आहे." },

    { t: "h2", x: "25. संपर्क" },
    { t: "p", x: "गाव तिथे उद्योजक इन्क्यूबेशन कौन्सिल (GTUIC)\nकंपनी कायदा २०१३ च्या Section 8 (कलम ८) अंतर्गत एक नोंदणीकृत संस्था (Non-profit Organization).\nRegistered Office: GAON TITHE UDYOJAK INCUBATION COUNCIL (GTUIC), 12, PLOT-12/14, ORICON HO,KAKUSHROO DUBASH MARG, MUMBAI, MAHARASHTRA, 400001\nOfficial Email: contact@gaontitheudyojak.com\nPrivacy / Grievance Email: gtuincubation@gmail.com\nContact Number:+91 88308 23679\nOfficial Portal: www.gaontitheudyojak.com" },

    { t: "h2", x: "APPLICANT CONSENT & DECLARATION" },
    { t: "p", x: "पोर्टलवर “I Agree / मी सहमत आहे” निवडून पुढे जाणे, नोंदणी करणे, अर्ज सादर करणे किंवा माहिती/कागदपत्रे अपलोड करणे याचा अर्थ अर्जदाराने:" },
    { t: "quote", x: "“मी या गोपनीयता धोरण मधील अटी वाचल्या असून त्या मला समजल्या आहेत. मी पोर्टलवर दिलेली माहिती स्वेच्छेने व स्वतःच्या जबाबदारीवर देत आहे. माझी माहिती गाव तिथे उद्योजक अभियानाच्या उद्देशाने संकलित, वापरली व आवश्यकतेनुसार GTUIC, MACCIA, संबंधित शासकीय विभाग, बँका, वित्तीय संस्था, योजना अंमलबजावणी संस्था व अभियानाशी संबंधित अधिकृत संस्थांसोबत शेअर केली जाऊ शकते, यास मी लागू कायद्यानुसार संमती देत आहे. माझ्याद्वारे दिलेल्या माहितीची सत्यता व अचूकतेची जबाबदारी माझी स्वतःची आहे.”" },
    { t: "p", x: "असे घोषित व मान्य केले आहे, असे समजण्यात येईल." },
];

export const privacyEn = [
    { t: "h1", x: "PRIVACY POLICY" },
    { t: "sub", x: "Gaon Tithe Udyojak Portal" },
    { t: "meta", x: "Effective Date: 1 July 2026" },
    { t: "meta", x: "Last Updated: 26 September 2026" },

    { t: "h2", x: "1. Introduction" },
    { t: "p", x: "The Gaon Tithe Udyojak Portal (“Portal”) is the official digital portal owned and controlled by the Gaon Tithe Udyojak Incubation Council (“GTUIC”), a non-profit organisation registered under Section 8 of the Companies Act, 2013." },
    { t: "p", x: "The Portal is being used by the GTUIC jointly with the Maharashtra Chamber of Commerce, Industry and Agriculture (MACCIA) for implementing the Gaon Tithe Udyojak Abhiyan (“Abhiyan”) across the State of Maharashtra." },
    { t: "p", x: "The purpose of this Privacy Policy is to clearly explain how personal, professional, financial and other necessary information collected from applicants/users through the Portal may be collected, used, stored, processed and, where necessary, shared." },
    { t: "p", x: "By registering on the Portal, submitting an application, providing information, uploading documents or using the relevant services/facilities of the Portal, the applicant shall be deemed to have read and understood the provisions of this Privacy Policy." },

    { t: "h2", x: "2. Purpose of the Gaon Tithe Udyojak Abhiyan" },
    { t: "p", x: "The primary objective of the Gaon Tithe Udyojak Abhiyan is to provide aspiring individuals in rural areas of Maharashtra with the guidance, training, support and opportunities required for entrepreneurship." },
    { t: "p", x: "Through the Abhiyan, subject to available resources and cooperation from relevant institutions, applicants may be supported in the following areas:" },
    { t: "ul", x: [
        "Entrepreneurship guidance;",
        "Guidance in selecting an appropriate business/industry;",
        "Development of business ideas;",
        "Entrepreneurship training and skill development;",
        "Guidance for business planning and preparation of project reports;",
        "Information regarding government schemes and related facilities;",
        "Guidance and support for government schemes, grants, loans or other financial assistance;",
        "Liaison and coordination, where necessary, with banks, financial institutions and other funding organisations;",
        "Assistance in identifying markets and market opportunities for products and services;",
        "Connecting applicants with industries, businesses, markets, experts, mentors and relevant institutions;",
        "Opportunities to participate in training programmes, workshops, seminars, entrepreneurship programmes and other initiatives; and",
        "Other support related to the objectives of the Abhiyan.",
    ] },

    { t: "h2", x: "3. Information That May Be Collected Through the Portal" },
    { t: "p", x: "Applicants may voluntarily provide the following types of information, as required for participating in the Abhiyan or receiving relevant support." },

    { t: "h3", x: "3.1 Personal Information" },
    { t: "ul", x: [
        "Full name;",
        "Mobile number;",
        "Email address;",
        "Date of birth/age;",
        "Gender, where required;",
        "Residential address;",
        "Village;",
        "Taluka;",
        "District;",
        "State;",
        "Educational information;",
        "Occupation/employment information;",
        "Experience;",
        "Skills; and",
        "Other relevant information.",
    ] },

    { t: "h3", x: "3.2 Entrepreneurship and Business-Related Information" },
    { t: "p", x: "Depending on the nature of the proposed or existing business:" },
    { t: "ul", x: [
        "Business name;",
        "Type of business;",
        "Nature of business;",
        "Proposed business idea;",
        "Business location;",
        "Details of an existing business;",
        "Product information;",
        "Service information;",
        "Business experience;",
        "Expected investment;",
        "Expected funding requirement;",
        "Estimated business expansion;",
        "Employment-generation potential;",
        "Market-related information;",
        "Business registration information; and",
        "Other necessary business-related information.",
    ] },

    { t: "h3", x: "3.3 Financial Information" },
    { t: "p", x: "Where required for the purposes of the Abhiyan or for providing guidance and support relating to financial assistance/government schemes:" },
    { t: "ul", x: [
        "Proposed project cost;",
        "Expected investment;",
        "Funding requirement;",
        "Financial information relating to an existing business;",
        "Information relating to banks/financial institutions;",
        "Loan-related information;",
        "Credit/financial eligibility-related information, where applicable; and",
        "Other information required for government schemes or financial assistance.",
    ] },

    { t: "h3", x: "3.4 Documents" },
    { t: "p", x: "Depending on the nature of the application, applicants may be required to provide documents such as:" },
    { t: "ul", x: [
        "Identity proof;",
        "Address proof;",
        "Business registration documents;",
        "Educational/training certificates;",
        "Licences and certificates;",
        "Project reports;",
        "Financial documents;",
        "Bank-related documents;",
        "Documents required for government schemes; and",
        "Other documents required for the relevant application.",
    ] },

    { t: "h2", x: "4. Information Voluntarily Provided by the Applicant" },
    { t: "p", x: "Information entered by the applicant on the Portal, documents uploaded by the applicant, or information otherwise provided by the applicant shall be considered to have been voluntarily provided by the applicant and at the applicant’s own responsibility." },
    { t: "p", x: "The applicant shall be fully responsible for ensuring that the information submitted is:" },
    { t: "ul", x: [
        "True and accurate;",
        "Complete;",
        "Up to date;",
        "Lawfully provided; and",
        "Appropriate for the purpose of the relevant application.",
    ] },
    { t: "p", x: "The GTUIC, MACCIA or other institutions/persons associated with the Abhiyan shall not be responsible for consequences arising from incorrect, incomplete, false, misleading or fraudulent information or documents submitted by the applicant." },

    { t: "h2", x: "5. Purpose of Collecting and Processing Information" },
    { t: "p", x: "Information collected from applicants may be used and processed for the following purposes:" },
    { t: "ul", x: [
        "Registering the applicant on the Portal;",
        "Receiving and processing applications for the Abhiyan;",
        "Understanding the applicant’s entrepreneurial potential, requirements and business;",
        "Providing guidance for selecting an appropriate industry/business;",
        "Providing training, guidance, mentoring and incubation facilities;",
        "Supporting the development of business ideas and projects;",
        "Providing guidance regarding government schemes and facilities;",
        "Providing necessary guidance and support for obtaining financial assistance through banks, financial institutions and other organisations;",
        "Facilitating access to market opportunities for products and services;",
        "Connecting applicants with relevant experts, trainers, mentors, industry organisations and partner organisations;",
        "Planning training programmes, workshops, events and other Abhiyan activities;",
        "Communicating with applicants regarding the Abhiyan;",
        "Evaluating and improving the effectiveness of the Abhiyan;",
        "Preparing statistical, research or analytical information;",
        "Preventing fraud, misuse or unauthorised use;",
        "Complying with legal, administrative or regulatory requirements; and",
        "Processing information for other lawful and necessary purposes related to the objectives of the Abhiyan.",
    ] },

    { t: "h2", x: "6. With Whom Information May Be Shared" },
    { t: "p", x: "For fulfilling the objectives of the Abhiyan or providing the guidance/support requested by the applicant, relevant applicant information may, where necessary, be shared with:" },
    { t: "ul", x: [
        "Gaon Tithe Udyojak Incubation Council (GTUIC);",
        "Maharashtra Chamber of Commerce, Industry and Agriculture (MACCIA);",
        "Relevant Central/State Government departments;",
        "Local authorities or relevant government agencies;",
        "Banks;",
        "Financial institutions;",
        "NBFCs or other authorised financial institutions;",
        "Organisations implementing government schemes;",
        "Industry associations;",
        "Training and educational institutions;",
        "Incubation and entrepreneurship support organisations;",
        "Mentors, consultants, trainers and subject-matter experts;",
        "Authorised partner organisations of the Abhiyan;",
        "Authorised service providers providing hosting, technology, security, communication or other technical services for the Portal; and",
        "Other authorised institutions/persons necessary for the purposes of the Abhiyan or for providing specific assistance requested by the applicant.",
    ] },
    { t: "p", x: "Any such exchange of information shall be relevant to the objectives of the Abhiyan, necessary for the relevant purpose and subject to applicable laws." },

    { t: "h2", x: "7. Consent for Sharing Information with Financial Institutions and Government Departments" },
    { t: "p", x: "If an applicant applies for a loan, financial assistance, government scheme, grant, subsidy, market support or other facility, it may be necessary to share the applicant’s required information with:" },
    { t: "ul", x: [
        "Government departments;",
        "Banks;",
        "Financial institutions;",
        "Scheme-implementing organisations; or",
        "Other relevant authorised organisations.",
    ] },
    { t: "p", x: "By submitting an application through the Portal, the applicant shall be deemed to have provided the necessary consent/permission for sharing such information to the extent required under applicable law." },

    { t: "h2", x: "8. Information Security" },
    { t: "p", x: "The GTUIC will endeavour to implement reasonable technical and administrative measures to protect applicant information from unauthorised access, misuse, alteration, unauthorised disclosure, loss or destruction." },
    { t: "p", x: "Such measures may include, as required:" },
    { t: "ul", x: [
        "Access controls;",
        "Authentication;",
        "Secure hosting;",
        "Data security measures;",
        "Authorised access;",
        "Monitoring;",
        "Backup and recovery arrangements; and",
        "Other appropriate security measures.",
    ] },
    { t: "p", x: "However, no internet-based system can be guaranteed to be completely secure. Therefore, the GTUIC cannot provide a complete guarantee against every possible risk arising from an unforeseen cyberattack, technical failure, unauthorised intrusion or other event beyond its control." },

    { t: "h2", x: "9. Data Retention" },
    { t: "p", x: "Applicant information may be retained for as long as necessary for Abhiyan operations, records and administrative purposes, training/guidance, government scheme or financial assistance processes, legal and regulatory requirements, or other relevant lawful purposes." },
    { t: "p", x: "Once the information is no longer required, it may be deleted, anonymised, archived or otherwise handled in accordance with applicable laws, regulations and the organisation’s data-retention requirements." },

    { t: "h2", x: "10. Responsibility After Information Is Shared with Third Parties" },
    { t: "p", x: "Where information is shared, at the applicant’s request or for the purposes of the Abhiyan, with a relevant government department, bank, financial institution, partner organisation or other authorised third party, the respective third party may apply its own rules, terms and privacy policy to its independent processing of such information." },
    { t: "p", x: "The GTUIC or MACCIA shall not be responsible for the independent privacy practices of such third parties or for matters outside their control." },

    { t: "h2", x: "11. Important Notice Regarding Government Schemes, Loans and Financial Assistance" },
    { t: "p", x: "The Abhiyan may provide guidance and support to applicants for accessing government schemes, loans, grants, subsidies, financial assistance or other financial facilities." },
    { t: "p", x: "However:" },
    { t: "ul", x: [
        "Registration on the Portal does not guarantee receipt of any government scheme benefit;",
        "Loan approval is not guaranteed;",
        "No grant, subsidy or financial assistance is guaranteed;",
        "Eligibility shall be determined according to the rules of the relevant government department or financial institution;",
        "The final decision shall rest with the relevant government department, bank or financial institution; and",
        "Applicants may be required to submit additional documents or information directly to the relevant institution.",
    ] },

    { t: "h2", x: "12. Notice Regarding Market and Business Opportunities" },
    { t: "p", x: "The Abhiyan may endeavour to facilitate access to markets, customers, traders, industry organisations or other business opportunities for applicants’ products or services." },
    { t: "p", x: "However, neither the Abhiyan nor the GTUIC guarantees any specific sale, order, customer, trade agreement, investment, business partnership, income or profit." },

    { t: "h2", x: "13. Applicant Responsibilities" },
    { t: "p", x: "While using the Portal and submitting an application, the applicant shall:" },
    { t: "ul", x: [
        "Provide true and accurate information;",
        "Provide required documents in an appropriate and valid form;",
        "Not provide false, incorrect or misleading information;",
        "Not provide another person’s information without their legal permission or authority;",
        "Maintain the security of their login credentials;",
        "Update information where necessary if there are any changes;",
        "Use the Abhiyan and Portal in compliance with applicable laws; and",
        "Not misuse the Portal, commit fraud or attempt unauthorised access.",
    ] },

    { t: "h2", x: "14. Accuracy of Information Provided by the Applicant" },
    { t: "p", x: "The applicant shall have full responsibility for the truthfulness, accuracy, completeness and authenticity of the information provided through the Portal." },
    { t: "p", x: "Where the GTUIC, MACCIA or any institution/person associated with the Abhiyan provides guidance based on information provided by the applicant, such institution/person shall not be held responsible for consequences arising from incorrect or incomplete information provided by the applicant." },
    { t: "p", x: "The GTUIC reserves the right to verify information or documents where necessary." },

    { t: "h2", x: "15. Use of Information Available on the Portal" },
    { t: "p", x: "Public information made available on the Portal is intended for information and guidance regarding the Abhiyan." },
    { t: "p", x: "If an applicant makes any business, financial investment, loan, government scheme or other decision based on information available on the Portal, the applicant should independently verify the relevant information with the concerned authorised department, financial institution or expert, wherever necessary." },

    { t: "h2", x: "16. Cookies and Technical Information" },
    { t: "p", x: "The Portal may use cookies, session technologies, analytics tools or similar technologies as necessary for its functioning." },
    { t: "p", x: "These may be used for:" },
    { t: "ul", x: [
        "Login/session management;",
        "Security;",
        "Portal functionality;",
        "Identifying technical issues;",
        "Improving user experience; and",
        "Aggregated usage analysis.",
    ] },

    { t: "h2", x: "17. Third-Party Websites" },
    { t: "p", x: "The Portal may contain links to websites of government departments, banks, financial institutions, partner organisations or other third parties." },
    { t: "p", x: "Upon accessing such websites, the respective third party’s Privacy Policy and Terms may apply." },
    { t: "p", x: "The GTUIC does not control such websites and shall not be responsible for their content, security or privacy practices." },

    { t: "h2", x: "18. Communications Related to the Abhiyan" },
    { t: "p", x: "After registering on the Portal or submitting an application, the applicant may be contacted regarding:" },
    { t: "ul", x: [
        "Application status;",
        "Training;",
        "Workshops;",
        "Entrepreneurship programmes;",
        "Mentoring/incubation;",
        "Government schemes;",
        "Financial assistance opportunities;",
        "Market opportunities;",
        "Abhiyan activities; and",
        "Other information directly related to the objectives of the Abhiyan.",
    ] },
    { t: "p", x: "Where required under applicable law, separate consent or opt-out facilities may be provided." },

    { t: "h2", x: "19. Privacy Rights and Grievance Redressal" },
    { t: "p", x: "Subject to applicable law, applicants shall be provided with the facility to exercise rights available to them concerning the processing of their personal information." },
    { t: "p", x: "Depending on the applicable circumstances, these may include:" },
    { t: "ul", x: [
        "Requesting information regarding the processing of their personal information;",
        "Requesting correction of inaccurate information;",
        "Requesting updating of information where necessary;",
        "Requesting deletion of information where permitted under applicable law;",
        "Requesting withdrawal of consent in relation to consent-based processing; and",
        "Raising a grievance relating to privacy or data processing.",
    ] },
    { t: "p", x: "The exercise of such rights shall be subject to applicable laws, rules and circumstances." },
    { t: "p", x: "Privacy / Grievance Officer: Rameshwar Pawar\nDesignation: President, Udyog Vichar Manch\nEmail: gtuincubation@gmail.com\nPhone: +91 88308 23679\nAddress:\nGAON TITHE UDYOJAK INCUBATION COUNCIL (GTUIC)\n12, PLOT-12/14, ORICON HO, KAKUSHROO DUBASH MARG,\nMUMBAI, MAHARASHTRA – 400001" },
    { t: "p", x: "No right or remedy mandatorily available under applicable law shall be restricted by this Privacy Policy." },

    { t: "h2", x: "20. Limitation of Responsibility" },
    { t: "p", x: "The Gaon Tithe Udyojak Abhiyan is an initiative intended to provide applicants with entrepreneurship guidance, training, incubation, facilitation and connections with various institutions." },
    { t: "p", x: "Registration or submission of an application through the Portal does not guarantee:" },
    { t: "ul", x: [
        "Starting of a business;",
        "Business success;",
        "Employment;",
        "Government scheme benefits;",
        "Grant or subsidy;",
        "Loan approval;",
        "Investment;",
        "Customers or market access;",
        "Business partnership;",
        "Sales or orders; or",
        "Income or profit.",
    ] },
    { t: "p", x: "The final decision regarding such matters shall rest with the relevant government department, bank, financial institution, customer, trader, partner organisation or other concerned third party." },

    { t: "h2", x: "21. Applicant Declaration Regarding Information and Consent" },
    { t: "p", x: "By submitting an application through the Portal, the applicant acknowledges and agrees that:" },
    { t: "p", x: "(a) The information provided on the Portal has been provided voluntarily and at the applicant’s own responsibility." },
    { t: "p", x: "(b) The information provided is, to the best of the applicant’s knowledge, true, accurate and complete." },
    { t: "p", x: "(c) The applicant understands that, for the purposes of the Abhiyan, necessary information may be shared with the GTUIC, MACCIA, relevant government departments, banks, financial institutions, scheme-implementing organisations, partner organisations, mentors, trainers and other authorised entities." },
    { t: "p", x: "(d) The applicant understands that sharing information with the relevant institution/department may be necessary for government schemes, loans or financial assistance." },
    { t: "p", x: "(e) The applicant shall be responsible for consequences arising from incorrect, false, incomplete or misleading information provided by them." },
    { t: "p", x: "(f) The applicant understands that applying through the Portal or participating in the Abhiyan does not guarantee any financial benefit, loan, grant, subsidy, business opportunity or other outcome." },
    { t: "p", x: "(g) The applicant confirms that they have read and understood the terms of this Privacy Policy and are applying through the Portal accordingly." },

    { t: "h2", x: "22. Complaints, Appeals and Legal Rights" },
    { t: "p", x: "Since the applicant voluntarily provides information through the Portal, the primary responsibility for the truthfulness and accuracy of such information shall remain with the applicant." },
    { t: "p", x: "During the operation of the Abhiyan, any guidance, processing or facilitation undertaken by the GTUIC, MACCIA or their authorised representatives may be based on information provided by the applicant and the rules of the relevant institutions." },
    { t: "p", x: "Accordingly, the GTUIC, MACCIA or institutions/persons associated with the Abhiyan shall not be held responsible for consequences arising from incorrect, incomplete or misleading information provided by the applicant." },
    { t: "p", x: "However, nothing in this Privacy Policy shall waive or restrict any statutory rights, data-protection rights, grievance mechanisms or judicial/legal remedies available to the applicant under applicable law." },

    { t: "h2", x: "23. Changes to this Privacy Policy" },
    { t: "p", x: "The GTUIC may modify this Privacy Policy as necessary." },
    { t: "p", x: "Changes may be made due to:" },
    { t: "ul", x: [
        "Changes in law;",
        "Government or regulatory directions;",
        "Changes in the nature of the Abhiyan;",
        "Changes in Portal functionality;",
        "Changes in data-processing practices; or",
        "Improvements to privacy and security practices.",
    ] },
    { t: "p", x: "The revised Privacy Policy will be published on the Portal and will include an updated “Last Updated” date." },

    { t: "h2", x: "24. Applicable Law" },
    { t: "p", x: "This Privacy Policy shall be governed by the applicable laws and regulations of India." },
    { t: "p", x: "The rights of applicants, responsibilities of the GTUIC and procedures relating to the processing of personal data shall be determined in accordance with applicable data-protection laws and regulations." },
    { t: "p", x: "The applicable provisions of the Digital Personal Data Protection Act, 2023 and the rules notified thereunder shall be complied with in accordance with the respective stages at which such provisions become applicable. The currently notified DPDP Rules, 2025 provide for certain provisions to come into effect in phases." },

    { t: "h2", x: "25. Contact" },
    { t: "p", x: "Gaon Tithe Udyojak Incubation Council (GTUIC)\nA registered non-profit organisation under Section 8 of the Companies Act, 2013.\nRegistered Office:\nGAON TITHE UDYOJAK INCUBATION COUNCIL (GTUIC)\n12, PLOT-12/14, ORICON HO, KAKUSHROO DUBASH MARG,\nMUMBAI, MAHARASHTRA – 400001\nOfficial Email: contact@gaontitheudyojak.com\nPrivacy / Grievance Email: gtuincubation@gmail.com\nContact Number: +91 88308 23679\nOfficial Portal: www.gaontitheudyojak.com" },

    { t: "h2", x: "APPLICANT CONSENT & DECLARATION" },
    { t: "p", x: "By selecting “I Agree / मी सहमत आहे”, proceeding on the Portal, registering, submitting an application or uploading information/documents, the applicant shall be deemed to have declared and agreed as follows:" },
    { t: "quote", x: "“I have read and understood the terms of this Privacy Policy. I am voluntarily providing the information submitted by me through the Portal and am providing such information at my own responsibility. I consent, to the extent permitted and required under applicable law, to my information being collected, used and, where necessary, shared for the purposes of the Gaon Tithe Udyojak Abhiyan with the GTUIC, MACCIA, relevant government departments, banks, financial institutions, scheme-implementing organisations and authorised institutions associated with the Abhiyan. I am responsible for the truthfulness and accuracy of the information provided by me.”" },
];
