// Terms of Service — verbatim content (do not edit wording)
// block types: h1 | sub | meta | h2 | h3 | p | ul | quote

export const termsMr = [
    { t: "h1", x: "सेवा अटी" },
    { t: "sub", x: "गाव तिथे उद्योजक पोर्टल" },
    { t: "meta", x: "प्रभावी दिनांक: १ जुलै २०२६" },
    { t: "meta", x: "शेवटचे अद्यतन: २६ सप्टेंबर २०२६" },

    { t: "h2", x: "1. प्रस्तावना" },
    { t: "p", x: "या सेवा अटी (“सेवा अटी”) गाव तिथे उद्योजक इन्क्यूबेशन कौन्सिल (“GTUIC”) द्वारे महाराष्ट्र चेंबर ऑफ कॉमर्स, इंडस्ट्री अँड अग्रीकल्चर (MACCIA) यांच्या सहकार्याने महाराष्ट्र राज्यात राबविण्यात येणाऱ्या गाव तिथे उद्योजक अभियान (“अभियान”) अंतर्गत वापरल्या जाणाऱ्या गाव तिथे उद्योजक पोर्टल (“पोर्टल”) च्या वापरास लागू राहतील." },
    { t: "p", x: "पोर्टलवर प्रवेश करणे, नोंदणी करणे, अर्ज सादर करणे किंवा पोर्टलचा अन्य कोणत्याही प्रकारे वापर करणे याचा अर्थ वापरकर्ता (“वापरकर्ता” किंवा “अर्जदार”) या सेवा अटी, पोर्टलवरील Privacy Policy आणि Disclaimer यांना मान्यता देत आहे, असे मानले जाईल." },
    { t: "p", x: "या सेवा अटी मान्य नसल्यास वापरकर्त्याने पोर्टलवर नोंदणी किंवा पोर्टलचा वापर करू नये." },

    { t: "h2", x: "2. पोर्टलचा उद्देश" },
    { t: "p", x: "पोर्टलचा उद्देश अभियानाशी संबंधित माहिती, नोंदणी, अर्ज प्रक्रिया, उद्योजकता मार्गदर्शन, प्रशिक्षण, mentoring, incubation, शासकीय योजनांची माहिती, आर्थिक सहाय्याबाबत facilitation, बाजारपेठीय संधी आणि इतर संबंधित उपक्रमांपर्यंत प्रवेश सुलभ करणे हा आहे." },
    { t: "p", x: "पोर्टलच्या माध्यमातून कोणत्याही वापरकर्त्यास कोणतेही व्यावसायिक, आर्थिक, शासकीय किंवा व्यावसायिक स्वरूपाचे निश्चित परिणाम मिळतील याची हमी दिली जात नाही." },

    { t: "h2", x: "3. पात्रता" },
    { t: "p", x: "पोर्टलचा वापर व्यक्ती, उद्योजक, इच्छुक उद्योजक, व्यवसाय तसेच अभियानाशी संबंधित पात्र व्यक्ती किंवा संस्थांकडून केला जाऊ शकतो." },
    { t: "p", x: "वापरकर्त्याने आवश्यकतेनुसार आपली पात्रता दर्शविणारी माहिती उपलब्ध करून द्यावी आणि संबंधित कार्यक्रम, योजना किंवा सुविधेच्या लागू अटींचे पालन करावे." },
    { t: "p", x: "वापरकर्ता लागू पात्रता निकष पूर्ण करत नसल्यास किंवा खोटी, अपूर्ण किंवा दिशाभूल करणारी माहिती दिल्यास GTUIC अर्ज नाकारू, स्थगित करू किंवा रद्द करू शकते." },

    { t: "h2", x: "4. नोंदणी व खाते" },
    { t: "p", x: "पोर्टलवरील काही सेवा किंवा सुविधांसाठी नोंदणी आवश्यक असू शकते." },
    { t: "p", x: "वापरकर्ता:" },
    { t: "ul", x: [
        "खरी, अचूक व पूर्ण माहिती देईल;",
        "आवश्यकतेनुसार माहिती अद्ययावत ठेवेल;",
        "Login credentials ची गोपनीयता राखेल;",
        "Login credentials अनधिकृत व्यक्तीस देणार नाही;",
        "खात्याचा अनधिकृत वापर झाल्याचा संशय असल्यास पोर्टल/GTUIC ला त्वरित कळवेल; आणि",
        "लागू कायद्याच्या मर्यादेत आपल्या खात्यामधून झालेल्या कृतींसाठी जबाबदार राहील.",
    ] },
    { t: "p", x: "GTUICला वापरकर्त्याने दिलेल्या माहितीची किंवा कागदपत्रांची पडताळणी करण्याचा अधिकार राहील." },

    { t: "h2", x: "5. अर्जदाराची माहिती व कागदपत्रे" },
    { t: "p", x: "पोर्टलवर सादर केलेली सर्व माहिती व कागदपत्रे:" },
    { t: "ul", x: [
        "अचूक व पूर्ण;",
        "खरी व वैध;",
        "कायदेशीररीत्या उपलब्ध करून दिलेली;",
        "अर्जाशी संबंधित; आणि",
        "दिशाभूल करणारी किंवा बनावट नसावीत.",
    ] },
    { t: "p", x: "वापरकर्त्याने आवश्यक अधिकार किंवा परवानगी नसताना दुसऱ्या व्यक्तीची माहिती किंवा कागदपत्रे सादर करू नयेत." },
    { t: "p", x: "अर्ज सादर केल्याने तो स्वीकारला, मंजूर झाला किंवा निवड झाली याची हमी मिळत नाही." },

    { t: "h2", x: "6. माहितीचा वापर" },
    { t: "p", x: "पोर्टलद्वारे सादर केलेली माहिती Privacy Policy मध्ये नमूद केलेल्या उद्देशांसाठी संकलित, प्रक्रिया, साठवली व आवश्यकतेनुसार शेअर केली जाऊ शकते." },
    { t: "p", x: "संबंधित सहाय्य किंवा सेवा उपलब्ध करून देण्यासाठी आवश्यक असल्यास वापरकर्त्याची माहिती शासकीय विभाग, बँका, वित्तीय संस्था, योजना अंमलबजावणी संस्था, mentors, trainers, partner organisations आणि इतर अधिकृत संस्थांसोबत शेअर केली जाऊ शकते, याची वापरकर्त्यास जाणीव आहे." },

    { t: "h2", x: "7. शासकीय योजना, कर्ज व आर्थिक सहाय्य" },
    { t: "p", x: "पोर्टलद्वारे शासकीय योजना, अनुदान, subsidy, कर्ज आणि इतर आर्थिक सहाय्याबाबत माहिती व facilitation उपलब्ध करून दिले जाऊ शकते." },
    { t: "p", x: "तथापि:" },
    { t: "ul", x: [
        "नोंदणी केल्याने पात्रता निश्चित होत नाही;",
        "अर्ज सादर केल्याने मंजुरीची हमी मिळत नाही;",
        "कर्ज, अनुदान, subsidy किंवा आर्थिक सहाय्य मिळण्याची हमी नाही;",
        "पात्रता व मंजुरी संबंधित प्राधिकरण किंवा वित्तीय संस्था ठरवते; आणि",
        "अंतिम निर्णय संबंधित प्राधिकरण किंवा संस्थेचा राहील.",
    ] },
    { t: "p", x: "कोणतीही आर्थिक किंवा कायदेशीर बांधिलकी स्वीकारण्यापूर्वी वापरकर्त्याने संबंधित पात्रता, अटी व नियमांची स्वतंत्रपणे पडताळणी करावी." },

    { t: "h2", x: "8. व्यवसाय, बाजारपेठ व व्यावसायिक संधी" },
    { t: "p", x: "अभियानाच्या माध्यमातून ग्राहक, बाजारपेठ, व्यापारी, उद्योग संस्था, गुंतवणूकदार, वित्तीय संस्था, mentors किंवा व्यावसायिक भागीदारांशी संपर्क साधण्यासाठी facilitation उपलब्ध करून दिले जाऊ शकते." },
    { t: "p", x: "तथापि, GTUIC किंवा MACCIA खालीलपैकी कोणत्याही बाबीची हमी देत नाही:" },
    { t: "ul", x: [
        "ग्राहक;",
        "विक्री;",
        "ऑर्डर;",
        "गुंतवणूक;",
        "भागीदारी;",
        "व्यवसायाची संधी;",
        "उत्पन्न;",
        "नफा; किंवा",
        "इतर कोणताही व्यावसायिक परिणाम.",
    ] },
    { t: "p", x: "वापरकर्ता आणि तृतीय पक्षामध्ये निर्माण होणारा कोणताही व्यवहार किंवा व्यावसायिक संबंध हा वापरकर्त्याच्या स्वतःच्या निर्णय व जबाबदारीवर राहील." },

    { t: "h2", x: "9. पोर्टलचा योग्य वापर" },
    { t: "p", x: "वापरकर्त्याने पोर्टलचा वापर केवळ कायदेशीर व वैध उद्देशांसाठी करावा." },
    { t: "p", x: "वापरकर्त्याने:" },
    { t: "ul", x: [
        "खोटी, बनावट किंवा दिशाभूल करणारी माहिती देऊ नये;",
        "दुसऱ्या व्यक्तीचे किंवा संस्थेचे रूप धारण करू नये;",
        "अनधिकृतपणे दुसऱ्या व्यक्तीचे खाते वापरू नये;",
        "पोर्टल किंवा त्याच्या प्रणालीमध्ये अनधिकृत प्रवेश मिळविण्याचा प्रयत्न करू नये;",
        "virus, malware किंवा इतर हानिकारक code वापरू नये;",
        "पोर्टलच्या कार्यप्रणाली किंवा सुरक्षेत अडथळा आणू नये;",
        "परवानगीशिवाय पोर्टलवरील माहितीचे scraping, copying किंवा systematic extraction करू नये;",
        "पोर्टलचा बेकायदेशीर, फसवणुकीचा किंवा गैरवापराचा उद्देशाने वापर करू नये;",
        "लागू कायद्यांचे किंवा इतरांच्या अधिकारांचे उल्लंघन करणारी सामग्री अपलोड करू नये;",
        "इतर कोणत्याही व्यक्तीचा छळ, धमकी किंवा नुकसान करण्यासाठी पोर्टलचा वापर करू नये; आणि",
        "कोणतीही security, authentication किंवा access-control व्यवस्था टाळण्याचा किंवा निष्प्रभ करण्याचा प्रयत्न करू नये.",
    ] },

    { t: "h2", x: "10. वापरकर्त्याने सादर केलेली सामग्री" },
    { t: "p", x: "पोर्टलवर मजकूर, कागदपत्रे, images, व्यवसायाची माहिती किंवा इतर सामग्री सादर करण्याची सुविधा असल्यास, अशा सामग्रीची जबाबदारी वापरकर्त्याची राहील." },
    { t: "p", x: "अशी सामग्री सादर करण्यासाठी आवश्यक अधिकार, परवानगी व कायदेशीर अधिकार वापरकर्त्याकडे असल्याची खात्री वापरकर्त्याने करावी." },
    { t: "p", x: "अभियानाचे संचालन व प्रशासन करण्यासाठी आवश्यक त्या मर्यादेत, वापरकर्ता GTUIC ला अशी सामग्री वापरणे, साठवणे, पुनरुत्पादित करणे व प्रक्रिया करण्याची परवानगी देतो. ही प्रक्रिया Privacy Policy व लागू कायद्यांच्या अधीन राहील." },

    { t: "h2", x: "11. बौद्धिक संपदा हक्क" },
    { t: "p", x: "अन्यथा नमूद केले नसल्यास, पोर्टल व त्यावरील design, layout, text, graphics, logos, branding, software आणि इतर सामग्री GTUICच्या किंवा संबंधित हक्कधारकांच्या मालकीची किंवा परवानाधारक सामग्री आहे." },
    { t: "p", x: "लागू कायद्यानुसार परवानगी नसल्यास, पूर्व लेखी परवानगीशिवाय अशा सामग्रीचे पुनरुत्पादन, बदल, वितरण, प्रकाशन, व्यावसायिक वापर किंवा derivative works तयार करता येणार नाहीत." },
    { t: "p", x: "पोर्टलवर वापरलेले तृतीय पक्षांचे trademarks, logos व content हे त्यांच्या संबंधित मालकांच्या मालकीचे राहतील." },

    { t: "h2", x: "12. तृतीय पक्षांच्या वेबसाइट्स व सेवा" },
    { t: "p", x: "पोर्टलवर तृतीय पक्षांच्या वेबसाइट्स, platforms, services किंवा resources चे links उपलब्ध असू शकतात." },
    { t: "p", x: "असे links केवळ वापरकर्त्यांच्या सोयीसाठी दिलेले असून ते GTUIC किंवा MACCIA कडून त्या तृतीय पक्षाची शिफारस किंवा मान्यता असल्याचे मानले जाऊ नये." },
    { t: "p", x: "तृतीय पक्षांच्या वेबसाइट्स किंवा सेवांची उपलब्धता, सामग्री, सुरक्षा, privacy practices, terms किंवा performance यासाठी GTUIC किंवा MACCIA जबाबदार राहणार नाहीत." },
    { t: "p", x: "अशा सेवांचा वापर करण्यापूर्वी वापरकर्त्यांनी संबंधित अटी व Privacy Policy तपासावी." },

    { t: "h2", x: "13. पोर्टलवरील माहितीची अचूकता" },
    { t: "p", x: "पोर्टलवरील माहिती अचूक व अद्ययावत ठेवण्यासाठी वाजवी प्रयत्न केले जाऊ शकतात. तथापि, शासकीय योजना, पात्रता, आर्थिक सहाय्य, बाजारपेठीय संधी, कार्यक्रम आणि इतर बाह्य बाबींशी संबंधित माहिती वेळोवेळी बदलू शकते." },
    { t: "p", x: "महत्त्वाच्या निर्णयांपूर्वी वापरकर्त्यांनी संबंधित अधिकृत प्राधिकरण किंवा संस्थेकडून माहितीची स्वतंत्र पडताळणी करावी." },
    { t: "p", x: "पोर्टलवर प्रकाशित केलेले Disclaimer हे पोर्टलवरील सामग्रीच्या वापरास लागू राहील." },

    { t: "h2", x: "14. पोर्टलची उपलब्धता व तांत्रिक समस्या" },
    { t: "p", x: "पोर्टल कार्यरत व उपलब्ध ठेवण्यासाठी GTUIC प्रयत्न करेल. तथापि, पोर्टल सतत किंवा अखंडितपणे उपलब्ध राहील याची हमी दिली जात नाही." },
    { t: "p", x: "खालील कारणांमुळे पोर्टल तात्पुरते अनुपलब्ध होऊ शकते:" },
    { t: "ul", x: [
        "Maintenance;",
        "तांत्रिक समस्या;",
        "System upgrades;",
        "Network किंवा infrastructure failure;",
        "Cyber incidents;",
        "Security measures;",
        "तृतीय पक्षांच्या सेवांमधील बिघाड; किंवा",
        "GTUICच्या वाजवी नियंत्रणाबाहेरील इतर परिस्थिती.",
    ] },
    { t: "p", x: "आवश्यकतेनुसार GTUIC पोर्टलचा कोणताही भाग बदलू, स्थगित करू किंवा बंद करू शकते." },

    { t: "h2", x: "15. खाते/प्रवेश स्थगित किंवा समाप्त करणे" },
    { t: "p", x: "खालील परिस्थितींमध्ये GTUIC वापरकर्त्याचा पोर्टलवरील प्रवेश तात्पुरता किंवा कायमस्वरूपी स्थगित, प्रतिबंधित किंवा समाप्त करू शकते:" },
    { t: "ul", x: [
        "वापरकर्त्याने या सेवा अटींचे उल्लंघन केले असल्यास;",
        "खोटी, बनावट किंवा दिशाभूल करणारी माहिती सादर केल्यास;",
        "पोर्टलचा गैरवापर केल्यास;",
        "अनधिकृत प्रवेश किंवा संशयास्पद कृती आढळल्यास;",
        "लागू कायद्यांचे उल्लंघन केल्यास; किंवा",
        "सुरक्षा, कायदेशीर किंवा प्रशासकीय कारणांसाठी अशी कारवाई आवश्यक असल्यास.",
    ] },
    { t: "p", x: "आवश्यकतेनुसार GTUIC अर्ज नाकारू किंवा रद्द करू शकते." },

    { t: "h2", x: "16. व्यावसायिक किंवा आर्थिक हमी नाही" },
    { t: "p", x: "अभियानाच्या माध्यमातून उपलब्ध करून दिलेली माहिती किंवा मार्गदर्शन हे स्वतंत्र व्यावसायिक सल्ल्याचा पर्याय मानले जाऊ नये." },
    { t: "p", x: "महत्त्वाचे निर्णय घेण्यापूर्वी आवश्यकतेनुसार वापरकर्त्याने पात्र कायदेशीर, आर्थिक, कर, तांत्रिक, व्यावसायिक किंवा इतर तज्ज्ञांचा स्वतंत्र सल्ला घ्यावा." },
    { t: "p", x: "अभियानातील सहभागामुळे व्यवसायाचे यश, रोजगार, निधी, गुंतवणूक, शासकीय लाभ किंवा व्यावसायिक परिणाम मिळण्याची कोणतीही हमी निर्माण होत नाही." },

    { t: "h2", x: "17. जबाबदारीची मर्यादा" },
    { t: "p", x: "लागू कायद्याने परवानगी दिलेल्या कमाल मर्यादेपर्यंत, पोर्टलचा वापर किंवा पोर्टलवरील माहितीवर अवलंबून राहिल्यामुळे उद्भवणाऱ्या कोणत्याही थेट, अप्रत्यक्ष, आकस्मिक, परिणामी किंवा इतर प्रकारच्या नुकसान, हानी, दायित्व, खर्च किंवा आर्थिक भारासाठी GTUIC, MACCIA किंवा त्यांचे संबंधित प्रतिनिधी जबाबदार राहणार नाहीत." },
    { t: "p", x: "यामध्ये खालील बाबींचा समावेश आहे:" },
    { t: "ul", x: [
        "पोर्टलचा वापर किंवा वापर करता न येणे;",
        "पोर्टलवरील माहितीवर अवलंबून राहणे;",
        "वापरकर्त्याने दिलेली चुकीची किंवा अपूर्ण माहिती;",
        "शासकीय विभाग, बँका, वित्तीय संस्था किंवा इतर तृतीय पक्षांचे निर्णय;",
        "अर्ज नाकारला जाणे;",
        "कर्ज, अनुदान, subsidy किंवा आर्थिक सहाय्य न मिळणे;",
        "व्यवसायाच्या संधी, ग्राहक, ऑर्डर किंवा गुंतवणूक न मिळणे;",
        "तृतीय पक्षांची कृती किंवा निष्क्रियता;",
        "तांत्रिक बिघाड, सेवा खंडित होणे किंवा विलंब; किंवा",
        "GTUICच्या वाजवी नियंत्रणाबाहेरील घटना.",
    ] },
    { t: "p", x: "लागू कायद्यानुसार ज्या जबाबदारीला वगळता किंवा मर्यादित करता येत नाही, त्या जबाबदारीवर या अटींचा परिणाम होणार नाही." },

    { t: "h2", x: "18. नुकसानभरपाई" },
    { t: "p", x: "लागू कायद्याने परवानगी दिलेल्या मर्यादेत, वापरकर्त्याने या सेवा अटींचे उल्लंघन केल्यामुळे किंवा पोर्टलच्या गैरवापरामुळे उद्भवणाऱ्या दावे, नुकसान, दायित्व, खर्च किंवा आर्थिक भारापासून GTUIC, MACCIA आणि त्यांचे संबंधित प्रतिनिधी यांना सुरक्षित ठेवण्यास व आवश्यकतेनुसार नुकसानभरपाई देण्यास वापरकर्ता सहमत आहे." },
    { t: "p", x: "यामध्ये विशेषतः:" },
    { t: "ul", x: [
        "वापरकर्त्याने या सेवा अटींचे उल्लंघन करणे;",
        "वापरकर्त्याने दिलेली खोटी, बनावट किंवा दिशाभूल करणारी माहिती;",
        "दुसऱ्या व्यक्तीची माहिती अनधिकृतपणे वापरणे;",
        "लागू कायदा किंवा तृतीय पक्षाच्या अधिकारांचे उल्लंघन; किंवा",
        "वापरकर्त्याने पोर्टलचा गैरवापर करणे",
    ] },
    { t: "p", x: "यांचा समावेश होतो." },

    { t: "h2", x: "19. गोपनीयता" },
    { t: "p", x: "पोर्टलद्वारे वैयक्तिक माहितीचे संकलन, वापर, प्रक्रिया, साठवण व शेअरिंग हे पोर्टलवर प्रकाशित केलेल्या Privacy Policy नुसार केले जाईल." },
    { t: "p", x: "पोर्टलचा वापर करून वापरकर्ता Privacy Policy ची दखल घेतो आणि लागू कायद्यानुसार आवश्यक त्या ठिकाणी संमती देतो." },

    { t: "h2", x: "20. Disclaimer / अस्वीकरण" },
    { t: "p", x: "पोर्टल व त्यावरील सामग्री ही माहिती, facilitation आणि मार्गदर्शनाच्या उद्देशाने उपलब्ध करून दिली जाते." },
    { t: "p", x: "पोर्टलवरील सर्व माहितीची अचूकता, पूर्णता, उपलब्धता किंवा विशिष्ट उद्देशासाठी योग्यतेची GTUIC किंवा MACCIA कोणतीही हमी देत नाहीत आणि अभियानातील सहभागामुळे कोणताही विशिष्ट परिणाम मिळेल याची हमी देत नाहीत." },
    { t: "p", x: "पोर्टलवर प्रकाशित केलेले Disclaimer हे या सेवा अटींचा अविभाज्य भाग मानले जाईल." },

    { t: "h2", x: "21. सेवा अटींमध्ये बदल" },
    { t: "p", x: "कायदे, नियम, अभियानाच्या गरजा, पोर्टलची functionality, तंत्रज्ञान, सुरक्षा पद्धती किंवा इतर वैध कारणांमुळे GTUIC या सेवा अटींमध्ये वेळोवेळी बदल करू शकते." },
    { t: "p", x: "सुधारित सेवा अटी पोर्टलवर प्रकाशित केल्या जातील आणि त्यावर संबंधित “Last Updated” तारीख नमूद केली जाईल." },
    { t: "p", x: "बदल प्रकाशित झाल्यानंतर पोर्टलचा वापर सुरू ठेवणे म्हणजे लागू कायद्याच्या मर्यादेत सुधारित सेवा अटींना मान्यता दिली आहे, असे मानले जाईल." },

    { t: "h2", x: "22. लागू कायदा व अधिकारक्षेत्र" },
    { t: "p", x: "या सेवा अटी भारतातील लागू कायदे व नियमांनुसार नियंत्रित केल्या जातील." },
    { t: "p", x: "पोर्टल, अभियान किंवा या सेवा अटींशी संबंधित कोणताही वाद लागू कायद्याच्या अधीन राहून भारतातील सक्षम न्यायालयांच्या अधिकारक्षेत्रात राहील." },
    { t: "p", x: "या सेवा अटींमुळे लागू कायद्यानुसार वापरकर्त्यास उपलब्ध असलेला कोणताही वैधानिक अधिकार किंवा कायदेशीर उपाय प्रतिबंधित केला जाणार नाही." },

    { t: "h2", x: "23. संपर्क" },
    { t: "p", x: "गाव तिथे उद्योजक इन्क्यूबेशन कौन्सिल (GTUIC)\nकंपनी कायदा, २०१३ च्या Section 8 अंतर्गत नोंदणीकृत Non-profit Organisation.\nRegistered Office:\n12, PLOT-12/14, ORICON HO, KAKUSHROO DUBASH MARG,\nMUMBAI, MAHARASHTRA – 400001\nOfficial Email: contact@gaontitheudyojak.com\nPrivacy / Grievance Email: gtuincubation@gmail.com\nContact Number: +91 88308 23679\nOfficial Portal: www.gaontitheudyojak.com" },
];

export const termsEn = [
    { t: "h1", x: "TERMS OF SERVICE" },
    { t: "sub", x: "Gaon Tithe Udyojak Portal" },
    { t: "meta", x: "Effective Date: 1 July 2026" },
    { t: "meta", x: "Last Updated: 26 September 2026" },

    { t: "h2", x: "1. Introduction" },
    { t: "p", x: "These Terms of Service (“Terms”) govern access to and use of the Gaon Tithe Udyojak Portal (“Portal”), operated by Gaon Tithe Udyojak Incubation Council (“GTUIC”) in association with the Maharashtra Chamber of Commerce, Industry and Agriculture (MACCIA) for the implementation of the Gaon Tithe Udyojak Abhiyan (“Abhiyan”) in Maharashtra." },
    { t: "p", x: "By accessing, registering on, submitting an application through or otherwise using the Portal, the user (“User” or “Applicant”) agrees to be bound by these Terms, the Privacy Policy and the Disclaimer published on the Portal." },
    { t: "p", x: "If the User does not agree with these Terms, the User should not register or use the Portal." },

    { t: "h2", x: "2. Purpose of the Portal" },
    { t: "p", x: "The Portal is intended to facilitate access to information, registration, applications, entrepreneurship guidance, training, mentoring, incubation, government-scheme information, financial-assistance facilitation, market opportunities and other initiatives associated with the Abhiyan." },
    { t: "p", x: "The Portal does not itself guarantee any business, financial, government or commercial outcome to any User." },

    { t: "h2", x: "3. Eligibility" },
    { t: "p", x: "The Portal may be used by individuals, entrepreneurs, aspiring entrepreneurs, businesses and other eligible persons or entities for purposes connected with the Abhiyan." },
    { t: "p", x: "The User must provide information regarding their eligibility whenever required and must comply with the applicable requirements of the relevant programme, scheme or facility." },
    { t: "p", x: "The GTUIC may refuse, suspend or cancel an application where the User does not satisfy applicable eligibility requirements or provides false, incomplete or misleading information." },

    { t: "h2", x: "4. Registration and Account" },
    { t: "p", x: "Certain services or features of the Portal may require registration." },
    { t: "p", x: "The User agrees to:" },
    { t: "ul", x: [
        "Provide true, accurate and complete information;",
        "Keep the information updated where necessary;",
        "Maintain the confidentiality of login credentials;",
        "Not share login credentials with unauthorised persons;",
        "Immediately notify the Portal/GTUIC of any suspected unauthorised access or misuse of the account; and",
        "Be responsible for activities carried out through the User's account, to the extent permitted under applicable law.",
    ] },
    { t: "p", x: "The GTUIC may require verification of the information or documents submitted by the User." },

    { t: "h2", x: "5. Applicant Information and Documents" },
    { t: "p", x: "The User is responsible for ensuring that all information and documents submitted through the Portal are:" },
    { t: "ul", x: [
        "Accurate and complete;",
        "Genuine and valid;",
        "Lawfully provided;",
        "Relevant to the application; and",
        "Not misleading or fraudulent.",
    ] },
    { t: "p", x: "The User must not submit information or documents belonging to another person without the necessary authority or permission." },
    { t: "p", x: "Submission of an application does not guarantee its acceptance, approval or selection." },

    { t: "h2", x: "6. Use of Information" },
    { t: "p", x: "Information submitted through the Portal may be collected, processed, stored and shared for the purposes described in the Privacy Policy." },
    { t: "p", x: "The User acknowledges that relevant information may, where necessary, be shared with government departments, banks, financial institutions, scheme-implementing organisations, mentors, trainers, partner organisations and other authorised entities for providing the relevant assistance or services." },

    { t: "h2", x: "7. Government Schemes, Loans and Financial Assistance" },
    { t: "p", x: "The Portal may provide information and facilitation relating to government schemes, grants, subsidies, loans and other financial assistance." },
    { t: "p", x: "However:" },
    { t: "ul", x: [
        "Registration does not guarantee eligibility;",
        "Submission of an application does not guarantee approval;",
        "Loan, grant, subsidy or financial assistance is not guaranteed;",
        "Eligibility and approval are determined by the relevant authority or financial institution; and",
        "The final decision rests solely with the relevant authority or institution.",
    ] },
    { t: "p", x: "Users should independently verify applicable eligibility requirements, terms and conditions before making any financial or legal commitment." },

    { t: "h2", x: "8. Business, Market and Commercial Opportunities" },
    { t: "p", x: "The Abhiyan may facilitate connections with customers, markets, traders, industry organisations, investors, financial institutions, mentors or business partners." },
    { t: "p", x: "However, the GTUIC and MACCIA do not guarantee any:" },
    { t: "ul", x: [
        "Customer;",
        "Sale;",
        "Order;",
        "Investment;",
        "Partnership;",
        "Business opportunity;",
        "Revenue;",
        "Profit; or",
        "Other commercial outcome.",
    ] },
    { t: "p", x: "Any transaction or business relationship established between a User and a third party shall be at the User's own discretion and responsibility." },

    { t: "h2", x: "9. Acceptable Use of the Portal" },
    { t: "p", x: "The User shall use the Portal only for lawful and legitimate purposes." },
    { t: "p", x: "The User shall not:" },
    { t: "ul", x: [
        "Provide false, fraudulent or misleading information;",
        "Impersonate another person or organisation;",
        "Use another person's account without authorisation;",
        "Attempt to gain unauthorised access to the Portal or its systems;",
        "Introduce viruses, malware or other harmful code;",
        "Interfere with the functioning or security of the Portal;",
        "Scrape, copy or systematically extract data from the Portal without authorisation;",
        "Use the Portal for unlawful, fraudulent or abusive activities;",
        "Upload content that violates applicable laws or the rights of others;",
        "Use the Portal to harass, threaten or harm another person; or",
        "Attempt to circumvent any security, authentication or access-control mechanism.",
    ] },

    { t: "h2", x: "10. User-Submitted Content" },
    { t: "p", x: "Where the Portal allows Users to submit text, documents, images, business information or other materials, the User remains responsible for such content." },
    { t: "p", x: "The User confirms that they have the necessary rights, permissions and authority to submit such content." },
    { t: "p", x: "The User grants the GTUIC, to the extent necessary for operating and administering the Abhiyan, permission to use, store, reproduce and process such submitted content for legitimate Abhiyan-related purposes, subject to the Privacy Policy and applicable law." },

    { t: "h2", x: "11. Intellectual Property" },
    { t: "p", x: "Unless otherwise stated, the Portal and its content, including its design, layout, text, graphics, logos, branding, software and other materials, are owned by or licensed to the GTUIC or the relevant rights holder." },
    { t: "p", x: "No User may reproduce, modify, distribute, publish, commercially exploit or create derivative works from such content without prior written permission, except where permitted under applicable law." },
    { t: "p", x: "Third-party trademarks, logos and content appearing on the Portal remain the property of their respective owners." },

    { t: "h2", x: "12. Third-Party Websites and Services" },
    { t: "p", x: "The Portal may contain links to third-party websites, platforms, services or resources." },
    { t: "p", x: "Such links are provided for convenience and do not constitute an endorsement or guarantee by the GTUIC or MACCIA." },
    { t: "p", x: "The GTUIC and MACCIA are not responsible for the availability, content, security, privacy practices, terms or performance of third-party websites or services." },
    { t: "p", x: "Users are advised to review the applicable terms and privacy policies before using such third-party services." },

    { t: "h2", x: "13. Accuracy of Portal Information" },
    { t: "p", x: "Reasonable efforts may be made to maintain accurate and updated information on the Portal. However, information relating to government schemes, eligibility, financial assistance, market opportunities, programmes and other external matters may change from time to time." },
    { t: "p", x: "Users should independently verify important information with the relevant official authority or institution before relying upon it." },
    { t: "p", x: "The Disclaimer published on the Portal shall also apply to the use of Portal content." },

    { t: "h2", x: "14. Availability and Technical Issues" },
    { t: "p", x: "The GTUIC will endeavour to keep the Portal operational and accessible. However, continuous or uninterrupted availability cannot be guaranteed." },
    { t: "p", x: "The Portal may occasionally be unavailable due to:" },
    { t: "ul", x: [
        "Maintenance;",
        "Technical issues;",
        "System upgrades;",
        "Network or infrastructure failures;",
        "Cyber incidents;",
        "Security measures;",
        "Third-party service failures; or",
        "Other circumstances beyond the reasonable control of the GTUIC.",
    ] },
    { t: "p", x: "The GTUIC may modify, suspend or discontinue any part of the Portal where reasonably necessary." },

    { t: "h2", x: "15. Suspension or Termination" },
    { t: "p", x: "The GTUIC may suspend, restrict or terminate a User's access to the Portal, temporarily or permanently, if:" },
    { t: "ul", x: [
        "The User violates these Terms;",
        "False, fraudulent or misleading information is submitted;",
        "The Portal is misused;",
        "Unauthorised access or suspicious activity is detected;",
        "The User violates applicable law; or",
        "Such action is reasonably necessary for security, legal or administrative purposes.",
    ] },
    { t: "p", x: "Where appropriate, the GTUIC may also cancel or reject an application." },

    { t: "h2", x: "16. No Professional or Financial Guarantee" },
    { t: "p", x: "Information or guidance provided through the Abhiyan should not be treated as a substitute for independent professional advice." },
    { t: "p", x: "Where appropriate, Users should obtain independent advice from qualified legal, financial, tax, technical, business or other professionals before making significant decisions." },
    { t: "p", x: "Participation in the Abhiyan does not create any guarantee of business success, employment, funding, investment, government benefits or commercial results." },

    { t: "h2", x: "17. Limitation of Liability" },
    { t: "p", x: "To the maximum extent permitted under applicable law, the GTUIC, MACCIA and their respective representatives shall not be liable for any direct, indirect, incidental, consequential or other loss, damage, liability, cost or expense arising from:" },
    { t: "ul", x: [
        "Use of or inability to use the Portal;",
        "Reliance on information available on the Portal;",
        "Incorrect or incomplete information submitted by a User;",
        "Decisions made by government departments, banks, financial institutions or other third parties;",
        "Rejection of applications;",
        "Failure to obtain loans, grants, subsidies or other financial assistance;",
        "Failure to obtain business opportunities, customers, orders or investments;",
        "Third-party acts or omissions;",
        "Technical failures, interruptions or delays; or",
        "Events beyond the reasonable control of the GTUIC.",
    ] },
    { t: "p", x: "Nothing in these Terms shall exclude or limit any liability that cannot lawfully be excluded or limited under applicable law." },

    { t: "h2", x: "18. Indemnity" },
    { t: "p", x: "To the extent permitted by applicable law, the User agrees to indemnify and hold harmless the GTUIC, MACCIA and their respective representatives from claims, losses, liabilities, damages, costs or expenses arising from:" },
    { t: "ul", x: [
        "Breach of these Terms by the User;",
        "False, fraudulent or misleading information submitted by the User;",
        "Unauthorised use of another person's information;",
        "Violation of applicable law or third-party rights; or",
        "Misuse of the Portal by the User.",
    ] },

    { t: "h2", x: "19. Privacy" },
    { t: "p", x: "The collection, use, processing, storage and sharing of personal information through the Portal shall be governed by the Privacy Policy published on the Portal." },
    { t: "p", x: "By using the Portal, the User acknowledges the Privacy Policy and provides consent wherever such consent is required under applicable law." },

    { t: "h2", x: "20. Disclaimer" },
    { t: "p", x: "The Portal and its content are provided for information, facilitation and guidance purposes." },
    { t: "p", x: "The GTUIC and MACCIA do not guarantee the accuracy, completeness, availability or suitability of all information available through the Portal and do not guarantee any specific outcome from participation in the Abhiyan." },
    { t: "p", x: "The Disclaimer published on the Portal forms an integral part of these Terms of Service." },

    { t: "h2", x: "21. Changes to the Terms" },
    { t: "p", x: "The GTUIC may modify these Terms from time to time due to changes in law, regulations, Abhiyan requirements, Portal functionality, technology, security practices or other legitimate reasons." },
    { t: "p", x: "The updated Terms will be published on the Portal along with the relevant “Last Updated” date." },
    { t: "p", x: "Continued use of the Portal after such changes are published shall constitute acceptance of the revised Terms, to the extent permitted under applicable law." },

    { t: "h2", x: "22. Governing Law and Jurisdiction" },
    { t: "p", x: "These Terms shall be governed by the applicable laws of India." },
    { t: "p", x: "Subject to applicable law, disputes arising out of or relating to the Portal, the Abhiyan or these Terms shall be subject to the jurisdiction of the competent courts in India." },
    { t: "p", x: "Nothing in these Terms shall restrict any statutory right or legal remedy available to a User under applicable law." },

    { t: "h2", x: "23. Contact" },
    { t: "p", x: "Gaon Tithe Udyojak Incubation Council (GTUIC)\nA registered non-profit organisation under Section 8 of the Companies Act, 2013.\nRegistered Office:\n12, PLOT-12/14, ORICON HO, KAKUSHROO DUBASH MARG,\nMUMBAI, MAHARASHTRA – 400001\nOfficial Email: contact@gaontitheudyojak.com\nPrivacy / Grievance Email: gtuincubation@gmail.com\nContact Number: +91 88308 23679\nOfficial Portal: www.gaontitheudyojak.com" },
];
